package com.aitrading.market;

import jakarta.annotation.PreDestroy;
import java.math.BigDecimal;
import java.net.http.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.springframework.stereotype.Service;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
import tools.jackson.databind.json.JsonMapper;

@Service
public final class CapitalStreamProvider implements MarketStreamProvider {
    private static final JsonMapper JSON=JsonMapper.builder().build();
    private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build();
    private final ScheduledExecutorService scheduler=Executors.newScheduledThreadPool(2,Thread.ofPlatform().daemon().name("capital-stream-",0).factory());
    final ConcurrentHashMap<String,Hub> hubs=new ConcurrentHashMap<>();
    private final CapitalMarketDataClient client;private final MarketSymbolRegistry registry;private final MarketProviderCandleStore candles;private final MarketLiveStateStore live;
    public CapitalStreamProvider(CapitalMarketDataClient client,MarketSymbolRegistry registry,MarketProviderCandleStore candles,MarketLiveStateStore live){this.client=client;this.registry=registry;this.candles=candles;this.live=live;}
    public String providerId(){return "CAPITAL";}public boolean configured(){return client.configured();}
    public SseEmitter subscribe(String requested,String timeframe){var route=registry.resolve(requested);if(!route.provider().equals("CAPITAL")||!route.realtimeSupported())throw new IllegalArgumentException("Invalid Capital stream symbol");MarketDataProvider.seconds(timeframe);if(!hubs.containsKey(route.providerSymbol())&&hubs.size()>=16)throw new CapitalDataFailure("CAPITAL_STREAM_CAPACITY",503);return hubs.computeIfAbsent(route.providerSymbol(),unused->new Hub(route)).add(requested,timeframe);}

    final class Hub implements WebSocket.Listener {
        final MarketSymbolRegistry.Route route;final Set<Subscription> subscriptions=ConcurrentHashMap.newKeySet();final StringBuilder text=new StringBuilder();final RealtimeTimeframeAggregator aggregator=new RealtimeTimeframeAggregator();
        volatile WebSocket socket;volatile CapitalMarketDataClient.Session session;volatile String status="CONNECTING";volatile boolean stopped;volatile long eventCount,reconnectDelay=1000;ScheduledFuture<?> retry,heartbeat,ping;
        Hub(MarketSymbolRegistry.Route route){this.route=route;connect();heartbeat=scheduler.scheduleAtFixedRate(()->publish("heartbeat",Map.of("at",Instant.now(),"status",status,"eventCount",eventCount)),10,10,TimeUnit.SECONDS);}
        SseEmitter add(String requested,String timeframe){if(subscriptions.size()>=256)throw new CapitalDataFailure("CAPITAL_STREAM_CAPACITY",503);var emitter=new SseEmitter(30*60_000L);var subscription=new Subscription(requested,timeframe,emitter);subscriptions.add(subscription);Runnable remove=()->{subscriptions.remove(subscription);if(subscriptions.isEmpty())stop();};emitter.onCompletion(remove);emitter.onTimeout(remove);emitter.onError(error->remove.run());send(subscription,"status",Map.of("status",status,"provider","CAPITAL"));var snapshot=aggregator.snapshot().get(timeframe);if(snapshot!=null)send(subscription,"snapshot",state(subscription,snapshot));return emitter;}
        synchronized void connect(){if(stopped)return;status="CONNECTING";live.status("CAPITAL",route.providerSymbol(),status);CapitalMarketDataClient.Session fresh;try{fresh=client.session();}catch(RuntimeException failure){scheduleReconnect("ERROR");return;}session=fresh;http.newWebSocketBuilder().connectTimeout(Duration.ofSeconds(10)).buildAsync(client.streamingUri(),this).whenComplete((value,error)->{if(error!=null)scheduleReconnect("ERROR");});}
        public void onOpen(WebSocket webSocket){synchronized(this){if(stopped){webSocket.abort();return;}socket=webSocket;status="CONNECTED";reconnectDelay=1000;subscribe(webSocket);ping=scheduler.scheduleAtFixedRate(this::ping,5,5,TimeUnit.MINUTES);}webSocket.request(1);}
        private void subscribe(WebSocket webSocket){var body=Map.of("destination","marketData.subscribe","correlationId",UUID.randomUUID().toString(),"cst",session.cst(),"securityToken",session.securityToken(),"payload",Map.of("epics",List.of(route.providerSymbol())));webSocket.sendText(JSON.writeValueAsString(body),true);}
        private void ping(){var value=socket;var currentSession=session;if(stopped||value==null||currentSession==null)return;var body=Map.of("destination","ping","correlationId",UUID.randomUUID().toString(),"cst",currentSession.cst(),"securityToken",currentSession.securityToken());value.sendText(JSON.writeValueAsString(body),true);}
        public CompletionStage<?> onText(WebSocket webSocket,CharSequence data,boolean last){synchronized(this){if(stopped||webSocket!=socket)return null;if(text.length()+data.length()>65536){text.setLength(0);webSocket.abort();scheduleReconnect("ERROR");return null;}text.append(data);if(last){try{handle(text.toString());}catch(RuntimeException malformed){}finally{text.setLength(0);}}}webSocket.request(1);return null;}
        private void handle(String raw){var event=JSON.readTree(raw);if(!event.path("status").asString().equals("OK"))return;String destination=event.path("destination").asString();if(destination.equals("marketData.subscribe")){status="SUBSCRIBED";live.status("CAPITAL",route.providerSymbol(),status);publish("status",Map.of("status",status,"provider","CAPITAL"));return;}if(!destination.equals("quote"))return;var payload=event.path("payload");if(!payload.path("epic").asString().equals(route.providerSymbol())||!payload.path("timestamp").isIntegralNumber()||!payload.path("bid").isNumber()||!payload.path("ofr").isNumber())return;Instant at=Instant.ofEpochMilli(payload.path("timestamp").asLong());BigDecimal bid=payload.path("bid").decimalValue(),offer=payload.path("ofr").decimalValue();String id=route.providerSymbol()+":"+payload.path("timestamp").asLong()+":"+bid.toPlainString()+":"+offer.toPlainString();var update=aggregator.accept(new RealtimeTimeframeAggregator.Quote(id,at,bid,offer));if(!update.accepted())return;eventCount++;if(update.finalizedM1()!=null)candles.upsert(route,List.of(update.finalizedM1()));status="LIVE";live.writeFrames("CAPITAL",route.providerSymbol(),update.price(),at,update.current(),status,eventCount,"MID");for(var subscription:subscriptions){var candle=update.current().get(subscription.timeframe());if(candle!=null)send(subscription,"candle",state(subscription,candle));}publish("status",Map.of("status",status,"provider","CAPITAL","eventCount",eventCount,"redis",live.health()));}
        private Map<String,Object> state(Subscription subscription,MarketDataProvider.Candle candle){var value=new LinkedHashMap<String,Object>();value.put("provider","CAPITAL");value.put("symbol",subscription.requested());value.put("timeframe",subscription.timeframe());value.put("candle",candle);value.put("openTime",candle.time());value.put("open",candle.open());value.put("high",candle.high());value.put("low",candle.low());value.put("close",candle.close());value.put("final",false);value.put("partial",true);value.put("priceBasis","MID");value.put("eventCount",eventCount);value.put("redisKeys",live.keys("CAPITAL",route.providerSymbol(),subscription.timeframe()));return Map.copyOf(value);}
        public CompletionStage<?> onClose(WebSocket webSocket,int code,String reason){synchronized(this){if(webSocket==socket)scheduleReconnect("DISCONNECTED");}return null;}public void onError(WebSocket webSocket,Throwable error){synchronized(this){if(webSocket==socket)scheduleReconnect("ERROR");}}
        synchronized void scheduleReconnect(String next){if(stopped||retry!=null&&!retry.isDone())return;var old=socket;socket=null;if(old!=null)old.abort();if(ping!=null)ping.cancel(false);client.invalidate(session);session=null;status="RECONNECTING";live.status("CAPITAL",route.providerSymbol(),status);publish("status",Map.of("status",status,"provider","CAPITAL","reason",next));long delay=reconnectDelay;reconnectDelay=Math.min(30_000,reconnectDelay*2);retry=scheduler.schedule(this::connect,delay,TimeUnit.MILLISECONDS);}
        void send(Subscription subscription,String event,Object value){try{subscription.emitter().send(SseEmitter.event().name(event).data(value));}catch(Exception disconnected){subscriptions.remove(subscription);}}
        void publish(String event,Object value){for(var subscription:subscriptions)send(subscription,event,value);}
        synchronized void stop(){if(stopped)return;stopped=true;if(socket!=null)socket.abort();if(retry!=null)retry.cancel(false);if(heartbeat!=null)heartbeat.cancel(false);if(ping!=null)ping.cancel(false);hubs.remove(route.providerSymbol(),this);live.status("CAPITAL",route.providerSymbol(),"DISCONNECTED");}
    }
    record Subscription(String requested,String timeframe,SseEmitter emitter) {}
    @PreDestroy void shutdown(){hubs.values().forEach(Hub::stop);scheduler.shutdownNow();}
}
