package com.aitrading.market;

import java.io.*;
import java.net.*;
import java.net.http.HttpClient;
import java.time.*;
import java.util.*;
import javax.net.ssl.*;
import tools.jackson.databind.json.JsonMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class CtraderMarketDataClient {
    record Listed(long id,String name,String description,String assetClass,String base,String quote,int digits,String timezone){}
    private static final Set<String> FIAT=Set.of("USD","EUR","GBP","JPY","CHF","AUD","CAD","NZD","CNH","HKD","SGD","NOK","SEK","DKK","PLN","CZK","HUF","TRY","ZAR","MXN");
    private final String clientId,clientSecret,environment;private final long accountId;private final CtraderTokenManager tokens;private volatile List<Listed> catalog;private volatile Instant catalogExpires=Instant.EPOCH;
    @Autowired
    public CtraderMarketDataClient(@Value("${aitrading.market.ctrader.client-id:}")String clientId,@Value("${aitrading.market.ctrader.client-secret:}")String clientSecret,@Value("${aitrading.market.ctrader.access-token:}")String accessToken,@Value("${aitrading.market.ctrader.refresh-token:}")String refreshToken,@Value("${aitrading.market.ctrader.access-token-expires-at:}")String accessTokenExpiresAt,@Value("${aitrading.market.ctrader.account-id:0}")long accountId,@Value("${aitrading.market.ctrader.environment:demo}")String environment){this(clientId,clientSecret,accessToken,refreshToken,accessTokenExpiresAt,accountId,environment,URI.create("https://openapi.ctrader.com/apps/token"));}
    private CtraderMarketDataClient(String clientId,String clientSecret,String accessToken,String refreshToken,String accessTokenExpiresAt,long accountId,String environment,URI tokenEndpoint){this.clientId=clean(clientId,256);this.clientSecret=clean(clientSecret,512);this.accountId=accountId;this.environment=environment==null?"":environment.strip().toLowerCase(Locale.ROOT);this.tokens=new CtraderTokenManager(this.clientId,this.clientSecret,clean(accessToken,2048),clean(refreshToken,2048),accessTokenExpiresAt,tokenEndpoint,HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(8)).build(),JsonMapper.builder().build(),Clock.systemUTC());}
    public boolean configured(){return !clientId.isEmpty()&&!clientSecret.isEmpty()&&!tokens.current().accessToken().isEmpty()&&!tokens.current().refreshToken().isEmpty()&&accountId>0&&Set.of("demo","live").contains(environment);}
    public synchronized List<Listed> catalog(){return loadCatalog(true);}
    private List<Listed> loadCatalog(boolean retryAfterAuthExpired){requireConfigured();if(catalog!=null&&Instant.now().isBefore(catalogExpires))return catalog;try(var session=open()){session.send(CtraderProtoCodec.symbols(accountId));var limited=session.expect(CtraderProtoCodec.SYMBOLS_RES).payload();var ids=CtraderProtoCodec.lightSymbolIds(limited);var details=new ArrayList<CtraderProtoCodec.Symbol>();for(int start=0;start<ids.size();start+=500){session.send(CtraderProtoCodec.symbolDetails(accountId,ids.subList(start,Math.min(ids.size(),start+500))));details.addAll(CtraderProtoCodec.symbols(limited,session.expect(CtraderProtoCodec.SYMBOL_BY_ID_RES).payload()));}
            var result=new ArrayList<Listed>();for(var item:details){String canonical=item.name().replaceAll("[^A-Za-z0-9]","").toUpperCase(Locale.ROOT);String base=canonical.length()>=6?canonical.substring(0,3):canonical,quote=canonical.length()>=6?canonical.substring(canonical.length()-3):"USD";String asset=assetClass(canonical);if(!asset.isEmpty())result.add(new Listed(item.id(),item.name(),item.description(),asset,base,quote,item.digits(),item.timezone()));}
            catalog=List.copyOf(result);catalogExpires=Instant.now().plus(Duration.ofMinutes(5));return catalog;
        }catch(CtraderDataFailure failure){if(retryAfterAuthExpired&&failure.authExpired())return loadCatalog(false);throw failure;}catch(Exception failure){throw new CtraderDataFailure("CTRADER_PROVIDER_UNAVAILABLE",502);}}
    public List<CtraderProtoCodec.Trendbar> history(long symbol,int period,Instant from,Instant to){return loadHistory(symbol,period,from,to,true);}
    private List<CtraderProtoCodec.Trendbar> loadHistory(long symbol,int period,Instant from,Instant to,boolean retryAfterAuthExpired){requireConfigured();if(catalog().stream().noneMatch(item->item.id()==symbol))throw new IllegalArgumentException("Unsupported cTrader symbol");try(var session=open()){session.send(CtraderProtoCodec.trendbars(accountId,symbol,period,from,to,1000));return CtraderProtoCodec.trendbars(session.expect(CtraderProtoCodec.TRENDBARS_RES).payload(),from,to);}catch(CtraderDataFailure failure){if(retryAfterAuthExpired&&failure.authExpired())return loadHistory(symbol,period,from,to,false);throw failure;}catch(Exception failure){throw new CtraderDataFailure("CTRADER_PROVIDER_UNAVAILABLE",502);}}
    Session openStream(long symbol)throws IOException {if(catalog().stream().noneMatch(item->item.id()==symbol))throw new IllegalArgumentException("Unsupported cTrader symbol");var session=open();session.send(CtraderProtoCodec.subscribe(accountId,symbol));session.expect(CtraderProtoCodec.SUBSCRIBE_SPOTS_RES);return session;}
    private Session open()throws IOException{requireConfigured();var token=tokens.beforeRequest();try{return openWithToken(token.accessToken());}catch(CtraderDataFailure failure){if(!failure.authExpired())throw failure;return openWithToken(tokens.afterAuthExpired(token.accessToken()).accessToken());}}
    private Session openWithToken(String accessToken)throws IOException{String host=environment.equals("live")?"live.ctraderapi.com":"demo.ctraderapi.com";var socket=(SSLSocket)SSLSocketFactory.getDefault().createSocket();try{socket.connect(new InetSocketAddress(host,5035),8000);socket.setSoTimeout(35000);var parameters=socket.getSSLParameters();parameters.setEndpointIdentificationAlgorithm("HTTPS");socket.setSSLParameters(parameters);socket.startHandshake();var session=new Session(socket,accessToken);session.send(CtraderProtoCodec.applicationAuth(clientId,clientSecret));session.expect(CtraderProtoCodec.APP_AUTH_RES);session.send(CtraderProtoCodec.accountAuth(accountId,accessToken));session.expect(CtraderProtoCodec.ACCOUNT_AUTH_RES);return session;}catch(Exception failure){try{socket.close();}catch(IOException ignored){}if(failure instanceof CtraderDataFailure dataFailure)throw dataFailure;if(failure instanceof IOException ioFailure)throw ioFailure;throw new IOException("cTrader connection failed",failure);}}
    final class Session implements AutoCloseable{private final SSLSocket socket;private final DataInputStream input;private final DataOutputStream output;private final String accessToken;Session(SSLSocket socket,String accessToken)throws IOException{this.socket=socket;this.accessToken=accessToken;input=new DataInputStream(new BufferedInputStream(socket.getInputStream()));output=new DataOutputStream(new BufferedOutputStream(socket.getOutputStream()));}
        synchronized void send(byte[] payload)throws IOException{if(payload.length>1_048_576)throw new CtraderDataFailure("CTRADER_FRAME_TOO_LARGE",502);output.writeInt(payload.length);output.write(payload);output.flush();}
        CtraderProtoCodec.Envelope read()throws IOException{int length=input.readInt();if(length<1||length>1_048_576)throw new CtraderDataFailure("CTRADER_FRAME_TOO_LARGE",502);byte[] raw=input.readNBytes(length);if(raw.length!=length)throw new EOFException("Incomplete cTrader frame");var message=CtraderProtoCodec.envelope(raw);if(message.type()==CtraderProtoCodec.ERROR_RES){var failure=new CtraderDataFailure(CtraderProtoCodec.error(message.payload()),502);if(failure.authExpired())tokens.afterAuthExpired(accessToken);throw failure;}return message;}
        CtraderProtoCodec.Envelope expect(int type)throws IOException{for(int count=0;count<100;count++){var message=read();if(message.type()==CtraderProtoCodec.HEARTBEAT){send(CtraderProtoCodec.heartbeat());continue;}if(message.type()==type)return message;}throw new CtraderDataFailure("CTRADER_RESPONSE_LIMIT",502);}
        public void close(){try{socket.close();}catch(IOException ignored){}}
    }
    static String assetClass(String canonical){if(canonical==null)return "";String symbol=canonical.toUpperCase(Locale.ROOT);if(symbol.startsWith("XAU")||symbol.startsWith("XAG")||symbol.startsWith("XPT")||symbol.startsWith("XPD")||symbol.contains("OIL")||symbol.startsWith("WTICO")||symbol.startsWith("BCO")||symbol.startsWith("NATGAS"))return "COMMODITY";if(symbol.length()!=6)return "";return FIAT.contains(symbol.substring(0,3))&&FIAT.contains(symbol.substring(3))?"FOREX":"";}
    private void requireConfigured(){if(!configured())throw new CtraderDataFailure("CTRADER_UNCONFIGURED",503);}private static String clean(String value,int max){value=value==null?"":value.strip();return value.length()<=max?value:"";}
}
