package com.aitrading.market;

import java.math.BigDecimal;
import java.net.URI;
import java.net.http.*;
import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;

@Service
public final class DukascopyHistoryProvider implements MarketDataProvider,HistoricalAvailabilityProvider {
    private record Spec(String canonical,String providerSymbol,String asset,String base,String quote,int priceScale,Instant availableFrom) {}
    private static final List<String> TF=List.of("1m");
    private static final Map<String,Spec> SPECS=specs();
    private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).followRedirects(HttpClient.Redirect.NEVER).build();
    public Capabilities capabilities(){return new Capabilities("DUKASCOPY","Dukascopy Public Data",List.of("FOREX","COMMODITY"),TF,true,false,false,false,false,true,true,false,false,false,true,"CONDITIONAL","CURATED_MAPPING",1440,"UTC",true,List.of("Daily BID M1 BI5 historical files","Public realtime feed not verified; no LIVE claim","BID candles are not silently merged with other providers"));}
    public List<Instrument> search(String query){if(query==null||query.length()>64)throw new IllegalArgumentException("Invalid search");String needle=query.toUpperCase(Locale.ROOT);return SPECS.values().stream().filter(s->(s.canonical()+" "+s.providerSymbol()).contains(needle)).map(this::instrument).toList();}
    public Instrument instrument(String symbol){return instrument(spec(symbol));}
    private Instrument instrument(Spec spec){return new Instrument("DUKASCOPY:"+spec.providerSymbol(),spec.canonical(),spec.providerSymbol(),"DUKASCOPY",spec.asset(),spec.base(),spec.quote(),"Dukascopy",spec.quote(),"SPOT","UTC",BigDecimal.ONE.scaleByPowerOfTen(-spec.priceScale()),null,null,null,null,"PROVIDER_VOLUME",null,BigDecimal.ONE,null,"QUANTITY_ONLY",List.of("HISTORICAL"),TF,"VERIFIED_FROM",spec.canonical());}
    public Instant historicalAvailableFrom(String symbol){return spec(symbol).availableFrom();}
    private static Spec spec(String symbol){if(symbol==null)throw new IllegalArgumentException("Invalid Dukascopy instrument");var value=SPECS.get(symbol.toUpperCase(Locale.ROOT).replace("/",""));if(value==null)throw new IllegalArgumentException("Unsupported Dukascopy instrument");return value;}
    public List<Candle> history(String symbol,String timeframe,Instant from,Instant to){var spec=spec(symbol);if(!"1m".equals(timeframe))throw new IllegalArgumentException("Dukascopy source timeframe is M1");MarketDataProvider.range(timeframe,from,to);if(Duration.between(from,to).toDays()>31)throw new IllegalArgumentException("Dukascopy request exceeds 32 days");var result=new TreeMap<Instant,Candle>();LocalDate day=from.atZone(ZoneOffset.UTC).toLocalDate(),last=to.minusNanos(1).atZone(ZoneOffset.UTC).toLocalDate();for(;!day.isAfter(last);day=day.plusDays(1)){for(int attempt=0;attempt<3;attempt++)try{for(var candle:download(spec,day))if(!candle.time().isBefore(from)&&candle.time().isBefore(to)&&result.putIfAbsent(candle.time(),candle)!=null)throw new DukascopyDataFailure("DUKASCOPY_DUPLICATE_CANDLE",502);break;}catch(DukascopyDataFailure failure){if(attempt==2)throw failure;try{Thread.sleep(250L<<attempt);}catch(InterruptedException interrupted){Thread.currentThread().interrupt();throw new DukascopyDataFailure("DUKASCOPY_INTERRUPTED",503);}}}return List.copyOf(result.values());}
    private List<Candle> download(Spec spec,LocalDate day){String path="/datafeed/"+spec.providerSymbol()+"/"+day.getYear()+"/"+String.format(Locale.ROOT,"%02d",day.getMonthValue()-1)+"/"+String.format(Locale.ROOT,"%02d",day.getDayOfMonth())+"/BID_candles_min_1.bi5";try{var request=HttpRequest.newBuilder(URI.create("https://datafeed.dukascopy.com"+path)).timeout(Duration.ofSeconds(20)).header("Accept","application/octet-stream").header("User-Agent","AITrading/1.0 market-data").GET().build();var response=http.send(request,HttpResponse.BodyHandlers.ofByteArray());if(response.statusCode()==404||response.statusCode()==204||response.body().length==0)return List.of();if(response.statusCode()==429)throw new DukascopyDataFailure("DUKASCOPY_RATE_LIMIT",429);if(response.statusCode()!=200||response.body().length>2_000_000)throw new DukascopyDataFailure("DUKASCOPY_HISTORY_UNAVAILABLE",502);return DukascopyBi5Decoder.decode(response.body(),day,spec.priceScale());}catch(DukascopyDataFailure failure){throw failure;}catch(InterruptedException interrupted){Thread.currentThread().interrupt();throw new DukascopyDataFailure("DUKASCOPY_INTERRUPTED",503);}catch(Exception failure){throw new DukascopyDataFailure("DUKASCOPY_HISTORY_UNAVAILABLE",502);}}
    private static Map<String,Spec> specs(){var rows=List.of(new Spec("EUR/USD","EURUSD","FOREX","EUR","USD",5,Instant.parse("2003-05-04T19:00:00Z")),new Spec("GBP/USD","GBPUSD","FOREX","GBP","USD",5,Instant.parse("2003-05-04T20:00:00Z")),new Spec("USD/JPY","USDJPY","FOREX","USD","JPY",3,Instant.parse("2003-05-04T17:00:00Z")),new Spec("AUD/USD","AUDUSD","FOREX","AUD","USD",5,Instant.parse("2003-08-03T17:00:00Z")),new Spec("USD/CAD","USDCAD","FOREX","USD","CAD",5,Instant.parse("2003-08-03T17:00:00Z")),new Spec("USD/CHF","USDCHF","FOREX","USD","CHF",5,Instant.parse("2003-05-04T20:00:00Z")),new Spec("NZD/USD","NZDUSD","FOREX","NZD","USD",5,Instant.parse("2003-08-03T17:00:00Z")),new Spec("XAU/USD","XAUUSD","COMMODITY","XAU","USD",3,Instant.parse("2003-05-05T00:01:00Z")),new Spec("XAG/USD","XAGUSD","COMMODITY","XAG","USD",3,Instant.parse("2003-05-04T23:09:00Z")),new Spec("XPT/USD","XPTCMDUSD","COMMODITY","XPT","USD",3,Instant.parse("2021-11-01T00:00:00Z")),new Spec("XPD/USD","XPDCMDUSD","COMMODITY","XPD","USD",3,Instant.parse("2021-07-04T22:00:00Z")));var map=new LinkedHashMap<String,Spec>();for(var row:rows){map.put(row.providerSymbol(),row);map.put(row.canonical().replace("/",""),row);}return Map.copyOf(map);}
}
