package com.aitrading.market;

import java.util.*;
import org.springframework.stereotype.Component;

@Component
public class ExistingMarketCatalogProvider implements InstrumentCatalogProvider {
    private final Map<String,MarketDataProvider> providers;
    public ExistingMarketCatalogProvider(List<MarketDataProvider> providers){var values=new TreeMap<String,MarketDataProvider>();for(var provider:providers)values.put(provider.capabilities().providerId(),provider);this.providers=Map.copyOf(values);}
    public List<Descriptor> descriptors(){return providers.values().stream().map(provider->{var value=provider.capabilities();boolean allowed=value.configured()&&value.displayAllowed()&&Set.of("ACCEPTED","CONDITIONAL").contains(value.licenseStatus());return new Descriptor(value.providerId(),value.assetClasses().stream().map(InstrumentCatalogProvider::normalizeAssetClass).distinct().toList(),20,allowed,value.requiresApiKey(),"6h");}).toList();}
    public List<Candidate> fetch(String providerId){var provider=providers.get(providerId);if(provider==null)throw new IllegalArgumentException("Unsupported catalog provider");try{return provider.search("").stream().map(item->candidate(item,20)).toList();}catch(CoinbaseDataFailure failure){throw new CatalogProviderFailure(failure.code(),failure.status()==429||failure.status()>=500);}catch(AlpacaDataFailure failure){throw new CatalogProviderFailure(failure.code(),failure.status()==429||failure.status()>=500);}catch(OandaDataFailure failure){throw new CatalogProviderFailure(failure.code(),failure.status()==429||failure.status()>=500);}catch(CtraderDataFailure failure){throw new CatalogProviderFailure(failure.code(),failure.status()==429||failure.status()>=500);}catch(FrankfurterDataFailure failure){throw new CatalogProviderFailure(failure.code(),failure.status()==429||failure.status()>=500);}}
    static Candidate candidate(MarketDataProvider.Instrument item,int priority){String asset=InstrumentCatalogProvider.normalizeAssetClass(item.assetClass());String symbol=item.providerSymbol().toUpperCase(Locale.ROOT);String key=item.base()!=null&&item.quote()!=null&&Set.of("CRYPTO","FOREX","COMMODITY").contains(asset)?InstrumentCatalogProvider.pairKey(asset,item.base(),item.quote(),"SPOT"):InstrumentCatalogProvider.listingKey(asset,item.exchange(),symbol);return new Candidate(key,asset,symbol,item.displaySymbol(),symbol,boundedName(item.name(),item.displaySymbol()),item.exchange(),null,null,null,item.currency(),item.base(),item.quote(),asset,null,null,item.provider(),priority,item.supportedModes(),item.supportedTimeframes(),item.timezone(),item.priceIncrement(),List.of());}
    private static String boundedName(String value,String fallback){String source=value==null||value.isBlank()?fallback:value;var clean=new StringBuilder();source.codePoints().filter(codePoint->!Character.isISOControl(codePoint)).limit(200).forEach(clean::appendCodePoint);String result=clean.toString().strip();return result.isEmpty()?fallback:result;}
}
