package com.aitrading.market;

import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;

@Service
public final class MarketHistoricalSyncService {
    public record Result(String canonicalSymbol,String provider,String providerSymbol,Instant requestedFrom,Instant effectiveFrom,Instant through,int fetched,int stored,String status,String errorCode,long elapsedMs) {}
    private final MarketSymbolRegistry registry;private final MarketProviderCandleStore store;private final Map<String,MarketDataProvider> providers;
    public MarketHistoricalSyncService(MarketSymbolRegistry registry,MarketProviderCandleStore store,List<MarketDataProvider> providers){this.registry=registry;this.store=store;var map=new TreeMap<String,MarketDataProvider>();for(var provider:providers)map.put(provider.capabilities().providerId(),provider);this.providers=Map.copyOf(map);}
    public Result sync(String symbol,Instant requestedFrom,Instant requestedTo){long started=System.nanoTime();var route=registry.resolve(symbol);var provider=providers.get(route.provider());if(provider==null||!provider.capabilities().configured())throw new IllegalArgumentException("Provider unavailable");Instant available=provider instanceof HistoricalAvailabilityProvider source?source.historicalAvailableFrom(route.providerSymbol()):route.declaredAvailableFrom();Instant from=max(requestedFrom,available),to=requestedTo.truncatedTo(java.time.temporal.ChronoUnit.MINUTES);Instant first=store.firstStored(route),last=store.lastStored(route);if(first!=null&&from.isBefore(first))to=min(to,first);else if(last!=null)from=max(from,last.plusSeconds(60));if(!to.isAfter(from))return new Result(route.canonicalSymbol(),route.provider(),route.providerSymbol(),requestedFrom,from,to,0,0,"READY",null,elapsed(started));store.state(route,available,last,"RUNNING",null);int fetched=0,stored=0;Instant cursor=from;try{while(cursor.isBefore(to)){Instant end=min(to,cursor.plus(window(route.provider())));var rows=provider.history(route.providerSymbol(),"1m",cursor,end);fetched+=rows.size();stored+=store.upsert(route,rows);cursor=end;store.state(route,available,rows.isEmpty()?store.lastStored(route):rows.getLast().time(),"PARTIAL",null);}Instant through=store.lastStored(route);store.state(route,available,through,"READY",null);return new Result(route.canonicalSymbol(),route.provider(),route.providerSymbol(),requestedFrom,from,through,fetched,stored,"READY",null,elapsed(started));}catch(RuntimeException failure){String code=code(failure);store.state(route,available,store.lastStored(route),"ERROR",code);return new Result(route.canonicalSymbol(),route.provider(),route.providerSymbol(),requestedFrom,from,store.lastStored(route),fetched,stored,"ERROR",code,elapsed(started));}}
    private static Duration window(String provider){return switch(provider){case "DUKASCOPY"->Duration.ofDays(1);default->Duration.ofDays(13);};}
    private static Instant max(Instant a,Instant b){return a.isAfter(b)?a:b;}private static Instant min(Instant a,Instant b){return a.isBefore(b)?a:b;}private static long elapsed(long started){return Duration.ofNanos(System.nanoTime()-started).toMillis();}
    private static String code(RuntimeException failure){if(failure instanceof DukascopyDataFailure value)return value.code();if(failure instanceof AlpacaDataFailure value)return value.code();if(failure instanceof CoinbaseDataFailure value)return value.code();return "MARKET_SYNC_FAILED";}
}
