package com.aitrading.image;
import com.aitrading.ai.*;import com.aitrading.api.ResourceFailure;import com.aitrading.auth.UserPrincipal;
import java.sql.*;import java.time.*;import java.util.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.authentication.BadCredentialsException;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import tools.jackson.databind.json.JsonMapper;
@Component public class ImageAnalysisStore{
 private final JdbcTemplate jdbc;private final JsonMapper json=JsonMapper.builder().build();public ImageAnalysisStore(JdbcTemplate j){jdbc=j;}
 public record Saved(UUID id,String question,String imageHash,int width,int height,AiImageAnalysis analysis,String provider,String model,Instant createdAt){}
 private Saved row(ResultSet r,int n)throws SQLException{try{return new Saved(r.getObject("id",UUID.class),r.getString("question"),r.getString("image_hash"),r.getInt("width"),r.getInt("height"),json.readValue(r.getString("result_json"),AiImageAnalysis.class),r.getString("provider"),r.getString("model"),r.getTimestamp("created_at").toInstant());}catch(Exception e){throw new SQLException("Invalid persisted analysis");}}
 private void current(UserPrincipal u,boolean lock){if(jdbc.queryForList("SELECT id FROM trading.app_user WHERE id=? AND credential_version=? FOR "+(lock?"UPDATE":"SHARE"),UUID.class,u.id(),u.credentialVersion()).isEmpty())throw new BadCredentialsException("Invalid session");}
 public Optional<Saved> replay(UserPrincipal u,UUID request,String hash){current(u,false);var rows=jdbc.query("SELECT * FROM trading.chart_image_analysis WHERE owner_id=? AND request_id=?",this::row,u.id(),request);if(rows.isEmpty())return Optional.empty();var saved=rows.getFirst();if(!hash.equals(jdbc.queryForObject("SELECT request_hash FROM trading.chart_image_analysis WHERE id=?",String.class,saved.id())))throw ResourceFailure.conflict();return Optional.of(saved);}
 public List<Saved> list(UserPrincipal u){current(u,false);return jdbc.query("SELECT * FROM trading.chart_image_analysis WHERE owner_id=? ORDER BY created_at DESC,id DESC LIMIT 50",this::row,u.id());}
 public Saved get(UserPrincipal u,UUID id){current(u,false);return jdbc.query("SELECT * FROM trading.chart_image_analysis WHERE id=? AND owner_id=?",this::row,id,u.id()).stream().findFirst().orElseThrow(ResourceFailure::missing);}
 @Transactional public Saved save(UserPrincipal u,UUID request,String requestHash,String question,String imageHash,byte[] png,int width,int height,AiImageAnalysis result,AiProvider.Configuration config){
  current(u,true);var prior=replay(u,request,requestHash);if(prior.isPresent())return prior.get();if(jdbc.queryForObject("SELECT count(*) FROM trading.chart_image_analysis WHERE owner_id=?",Long.class,u.id())>=50)throw ResourceFailure.conflict();UUID id=UUID.randomUUID();String encoded;try{encoded=json.writeValueAsString(result);}catch(Exception e){throw new AiFailure(AiFailure.Code.AI_INVALID_RESPONSE);}try{jdbc.update("INSERT INTO trading.chart_image_analysis(id,owner_id,request_id,request_hash,question,image_hash,image_png,width,height,result_json,provider,model) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",id,u.id(),request,requestHash,question,imageHash,png,width,height,encoded,config.provider(),config.model());}catch(DuplicateKeyException race){return replay(u,request,requestHash).orElseThrow(ResourceFailure::conflict);}return get(u,id);
 }
}
