package com.aitrading.image;
import com.aitrading.ai.*;import com.aitrading.auth.UserPrincipal;import com.aitrading.market.MarketCsvParser;import com.aitrading.strategy.StrategyService;
import java.awt.image.BufferedImage;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import javax.imageio.*;import javax.imageio.stream.ImageInputStream;import org.springframework.stereotype.Service;import org.springframework.web.multipart.MultipartFile;
@Service public class ImageAnalysisService{
 public static final int MAX_BYTES=2*1024*1024;private final AiProvider provider;private final ImageAnalysisStore store;public ImageAnalysisService(AiProvider p,ImageAnalysisStore s){provider=p;store=s;}
 private record Canonical(byte[] png,int width,int height,String hash){}
 public List<ImageAnalysisStore.Saved> list(UserPrincipal u){return store.list(u);}public ImageAnalysisStore.Saved get(UserPrincipal u,UUID id){return store.get(u,id);}
 public ImageAnalysisStore.Saved analyze(UserPrincipal u,String requestId,String question,MultipartFile file){UUID request=StrategyService.id(requestId);question=text(question);Canonical image=canonical(file);String intent=MarketCsvParser.hash(question+"\n"+image.hash());var prior=store.replay(u,request,intent);if(prior.isPresent())return prior.get();var config=provider.configuration();if(!config.configured())throw new AiFailure(AiFailure.Code.AI_UNCONFIGURED);AiImageAnalysis result=provider.analyzeImage(new AiProvider.ImageRequest(image.png(),question));return store.save(u,request,intent,question,image.hash(),image.png(),image.width(),image.height(),result,config);}
 private static String text(String s){if(s==null||(s=s.strip()).isEmpty()||s.length()>1000||s.getBytes(StandardCharsets.UTF_8).length>2000||s.codePoints().anyMatch(c->c==0||(Character.isISOControl(c)&&c!='\n'&&c!='\r'&&c!='\t')))throw new IllegalArgumentException("Invalid image analysis");return s;}
 private static Canonical canonical(MultipartFile file){try{if(file==null||file.isEmpty()||file.getSize()>MAX_BYTES||!Set.of("image/png","image/jpeg").contains(file.getContentType()))throw bad();byte[] raw=file.getBytes();boolean png=raw.length>=12&&raw[0]==(byte)137&&raw[1]==80&&raw[2]==78&&raw[3]==71&&raw[raw.length-8]=='I'&&raw[raw.length-7]=='E'&&raw[raw.length-6]=='N'&&raw[raw.length-5]=='D';boolean jpeg=raw.length>=4&&raw[0]==(byte)0xff&&raw[1]==(byte)0xd8&&raw[raw.length-2]==(byte)0xff&&raw[raw.length-1]==(byte)0xd9;if(!(png&&file.getContentType().equals("image/png"))&&!(jpeg&&file.getContentType().equals("image/jpeg")))throw bad();BufferedImage decoded;try(ImageInputStream input=ImageIO.createImageInputStream(new ByteArrayInputStream(raw))){var readers=ImageIO.getImageReaders(input);if(!readers.hasNext())throw bad();var reader=readers.next();try{reader.setInput(input,true,true);int w=reader.getWidth(0),h=reader.getHeight(0);if(w<1||h<1||w>4096||h>4096||(long)w*h>16_000_000)throw bad();decoded=reader.read(0);if(decoded==null)throw bad();}finally{reader.dispose();}}var out=new ByteArrayOutputStream();if(!ImageIO.write(decoded,"png",out))throw bad();byte[] canonical=out.toByteArray();if(canonical.length>MAX_BYTES)throw bad();return new Canonical(canonical,decoded.getWidth(),decoded.getHeight(),sha(canonical));}catch(Exception e){if(e instanceof IllegalArgumentException i)throw i;throw bad();}}
 private static String sha(byte[] bytes){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private static IllegalArgumentException bad(){return new IllegalArgumentException("Invalid image analysis");}
}
