import * as api from './api'

const account='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
const documentId='11111111-1111-4111-8111-111111111111'
const answer:api.Answer={kind:'answer',answer:'Synthetic answer',assumptions:[],provider:'gemini',model:'gemini-3.5-flash',citations:[{documentId,version:1,chunkIndex:0,pageNumber:null,title:'Evidence',excerpt:'Synthetic closed-candle evidence.',hash:'a'.repeat(64)}]}
const response=(body:unknown,status=200)=>new Response(status===204?null:JSON.stringify(body),{status})
const token=()=>response({headerName:'X-CSRF-TOKEN',token:'synthetic'})

afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()})

it('uploads a bounded multipart body with account binding and CSRF',async()=>{const saved={document:{id:documentId,title:'Evidence',currentVersion:1,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'},version:{documentId,version:1,filename:'safe.txt',mediaType:'text/plain',contentHash:'a'.repeat(64),pageCount:0,createdAt:'2026-09-01T00:00:00Z'}};const net=vi.fn().mockResolvedValueOnce(token()).mockResolvedValueOnce(response(saved));vi.stubGlobal('fetch',net);const file=new File(['synthetic'],'safe.txt',{type:'text/plain'});await expect(api.upload(file,'Evidence',0,null,'22222222-2222-4222-8222-222222222222',account)).resolves.toEqual(saved);const options=net.mock.calls[1][1];expect(new Headers(options.headers).get('X-Workspace-User')).toBe(account);expect(new Headers(options.headers).get('X-CSRF-TOKEN')).toBe('synthetic');expect(options.body).toBeInstanceOf(FormData);expect(options.body.get('file')).toBe(file);expect(options.body.get('expectedVersion')).toBe('0')})
it('deletes with JSON expected version, account binding and CSRF',async()=>{const net=vi.fn().mockResolvedValueOnce(token()).mockResolvedValueOnce(response(null,204));vi.stubGlobal('fetch',net);await api.remove(documentId,1,account);expect(net.mock.calls[1][0]).toContain(`/documents/${documentId}`);const options=net.mock.calls[1][1];expect(JSON.parse(options.body)).toEqual({expectedVersion:1});expect(new Headers(options.headers).get('X-Workspace-User')).toBe(account);expect(new Headers(options.headers).get('X-CSRF-TOKEN')).toBe('synthetic')})

it('accepts exact citations and fails closed on malformed or surplus fields',async()=>{const malformed=[{...answer,ownerId:account},{...answer,citations:[{...answer.citations[0],hash:'short'}]},{...answer,citations:[{...answer.citations[0],pageNumber:51}]},{...answer,provider:null},{...answer,kind:'insufficient',citations:answer.citations}];const net=vi.fn().mockResolvedValueOnce(token()).mockResolvedValueOnce(response(answer));for(const value of malformed)net.mockResolvedValueOnce(token()).mockResolvedValueOnce(response(value));vi.stubGlobal('fetch',net);await expect(api.ask('What is supported?',account)).resolves.toEqual(answer);for(const value of malformed){void value;await expect(api.ask('What is supported?',account)).rejects.toThrow('Invalid document response')}})
