package com.aitrading.ai;
import static org.assertj.core.api.Assertions.*;import com.aitrading.api.ResourceFailure;import com.aitrading.image.*;import java.awt.Color;import java.awt.image.BufferedImage;import java.io.*;import java.util.*;import javax.imageio.ImageIO;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.mock.web.MockMultipartFile;import org.springframework.test.annotation.DirtiesContext;
@DirtiesContext(classMode=DirtiesContext.ClassMode.BEFORE_CLASS)class ImageAnalysisApiTests extends AiApiTests{
 @Autowired ImageAnalysisService images;
 byte[] image(String format)throws Exception{var value=new BufferedImage(80,40,BufferedImage.TYPE_INT_RGB);var g=value.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,80,40);g.setColor(Color.GREEN);g.drawLine(5,35,75,5);g.dispose();var out=new ByteArrayOutputStream();ImageIO.write(value,format,out);return out.toByteArray();}
 MockMultipartFile file(String type,byte[] bytes){return new MockMultipartFile("file","ignored-name",type,bytes);}
 @Test void canonicalOwnedPersistenceReplayAndRestartReadAreExact()throws Exception{String request=UUID.randomUUID().toString();var saved=images.analyze(user(a),request,"Analyze synthetic chart",file("image/jpeg",image("jpeg")));assertThat(saved.width()).isEqualTo(80);assertThat(saved.height()).isEqualTo(40);assertThat(saved.analysis().visibleEvidence()).hasSize(1);assertThat(jdbc.queryForObject("SELECT octet_length(image_png) FROM trading.chart_image_analysis WHERE id=?",Integer.class,saved.id())).isPositive();assertThat(jdbc.queryForObject("SELECT encode(substring(image_png from 1 for 8),'hex') FROM trading.chart_image_analysis WHERE id=?",String.class,saved.id())).isEqualTo("89504e470d0a1a0a");assertThat(images.analyze(user(a),request,"Analyze synthetic chart",file("image/jpeg",image("jpeg"))).id()).isEqualTo(saved.id());assertThat(probe.calls.get()).isEqualTo(1);assertThat(images.list(user(b))).isEmpty();assertThatThrownBy(()->images.get(user(b),saved.id())).isInstanceOf(ResourceFailure.class);assertThat(new ImageAnalysisService(probe,new ImageAnalysisStore(jdbc)).get(user(a),saved.id()).imageHash()).isEqualTo(saved.imageHash());}
 @Test void invalidImageQuestionReplayAndProviderFailuresFailClosed()throws Exception{byte[] png=image("png");for(var bad:List.of(file("image/jpeg",png),file("image/png",Arrays.copyOf(png,png.length-1)),file("text/plain",png),file("image/png",new byte[0]),file("image/png",new byte[2*1024*1024+1])))assertThatThrownBy(()->images.analyze(user(a),UUID.randomUUID().toString(),"Synthetic",bad)).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->images.analyze(user(a),UUID.randomUUID().toString()," ",file("image/png",png))).isInstanceOf(IllegalArgumentException.class);String request=UUID.randomUUID().toString();images.analyze(user(a),request,"First",file("image/png",png));assertThatThrownBy(()->images.analyze(user(a),request,"Changed",file("image/png",png))).isInstanceOf(ResourceFailure.class);probe.mode.set("rate");assertThatThrownBy(()->images.analyze(user(a),UUID.randomUUID().toString(),"Rate",file("image/png",png))).isInstanceOf(AiFailure.class);}
 @Test void actualHttpAuthenticationAccountCsrfAndOwnerReadAreEnforced()throws Exception{var saved=images.analyze(user(a),UUID.randomUUID().toString(),"HTTP synthetic",file("image/png",image("png")));assertThat(tree(call(a,"GET","/api/image-analyses/"+saved.id(),null),200).get("id").asString()).isEqualTo(saved.id().toString());tree(call(b,"GET","/api/image-analyses/"+saved.id(),null),404);var anonymous=new Actor(java.net.http.HttpClient.newHttpClient(),null,null,"");tree(call(anonymous,"GET","/api/image-analyses",null),401);assertThat(send(a,"POST","/api/image-analyses","",null,Map.of("Content-Type","multipart/form-data; boundary=x")).statusCode()).isEqualTo(403);assertThat(send(a,"GET","/api/image-analyses","",null,Map.of("X-Workspace-User",b.id().toString())).statusCode()).isEqualTo(401);}
}
