package com.aitrading.ai;
import static org.assertj.core.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.Test;import org.springframework.test.annotation.DirtiesContext;
@DirtiesContext(classMode=DirtiesContext.ClassMode.BEFORE_CLASS)
class JournalEvaluationAiApiTests extends AiApiTests {
  UUID journal(Actor actor){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO trading.journal_entry(id,owner_id,version,symbol,timeframe,settlement_currency,side,state,quantity,entry_price,entry_fee,exit_fee,entry_time,entry_reason,notes) VALUES(?,?,1,'TEST_USD','1h','USD','LONG','OPEN',1,100,0,0,clock_timestamp()-interval '1 hour','closed candle breakout','synthetic only')",id,actor.id());return id;}
  String evalPath(UUID id){return "/api/journal/"+id+"/evaluations";}
  @Test void evaluatesOwnedSavedVersionWithBoundedGroundedRubricAndReplay()throws Exception{UUID id=journal(a),request=UUID.randomUUID();var body=Map.of("requestId",request,"expectedVersion",1);var first=tree(call(a,"POST",evalPath(id),body),200);assertThat(first.get("state").asString()).isEqualTo("READY");assertThat(first.get("score").asInt()).isEqualTo(53);assertThat(first.get("result").get("rubric")).hasSize(4);assertThat(tree(call(a,"POST",evalPath(id),body),200)).isEqualTo(first);assertThat(probe.calls.get()).isEqualTo(1);assertThat(probe.capturedContext(0).getFirst()).contains("closed candle breakout").doesNotContain("synthetic only");assertThat(call(b,"GET",evalPath(id),null).statusCode()).isEqualTo(404);}
  @Test void insufficientMalformedProviderAndStaleSnapshotNeverFabricateScore()throws Exception{UUID id=journal(a);probe.mode.set("insufficient");var insufficient=tree(call(a,"POST",evalPath(id),Map.of("requestId",UUID.randomUUID(),"expectedVersion",1)),200);assertThat(insufficient.get("state").asString()).isEqualTo("INSUFFICIENT");assertThat(insufficient.get("score").isNull()).isTrue();probe.mode.set("malformed-evidence");var failed=tree(call(a,"POST",evalPath(id),Map.of("requestId",UUID.randomUUID(),"expectedVersion",1)),200);assertThat(failed.get("state").asString()).isEqualTo("FAILED");assertThat(failed.get("errorCode").asString()).isEqualTo("AI_INVALID_RESPONSE");assertThat(call(a,"POST",evalPath(id),Map.of("requestId",UUID.randomUUID(),"expectedVersion",2)).statusCode()).isEqualTo(409);}
  @Test void csrfExpectedAccountUnknownFieldsAndIdsFailBeforeProvider()throws Exception{UUID id=journal(a);var body=Map.of("requestId",UUID.randomUUID(),"expectedVersion",1);assertThat(send(a,"POST",evalPath(id),json.writeValueAsString(body),null,Map.of()).statusCode()).isEqualTo(403);assertThat(send(a,"POST",evalPath(id),json.writeValueAsString(body),a.csrf(),Map.of("X-Workspace-User",b.id().toString())).statusCode()).isEqualTo(401);var extra=new HashMap<String,Object>(body);extra.put("prompt","override");assertThat(call(a,"POST",evalPath(id),extra).statusCode()).isEqualTo(400);assertThat(probe.calls.get()).isZero();}
}
