import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { buttonClass } from '../auth/AuthForm'
import { Modal } from '../components/Modal'
import { ChartToolsRail, ChartUtilities } from '../components/ChartControls'
import { Icon } from '../components/Icon'
import { CandleChart } from './CandleChart'
import { aggregateCandles, normalizeTimeframe, timeframeAvailability, timeframeLabel, type Timeframe } from './chartMath'
import { defaultChartSettings, type ChartSettings, type ChartType, type Drawing, type DrawingTool, type IndicatorConfig } from './chartTypes'
import { ImportForm } from './ImportForm'
import { useMarket } from './MarketContext'

const iconButton = 'icon-tool grid h-8 w-8 shrink-0 place-items-center rounded-md text-slate-500 transition hover:bg-slate-800 hover:text-slate-100 focus-visible:ring-2 focus-visible:ring-slate-300 disabled:opacity-35'
const menuPanel = 'absolute left-0 top-9 z-40 min-w-44 rounded-lg border border-slate-700 bg-slate-900 p-1.5 shadow-2xl'
const menuRow = 'flex min-h-9 w-full items-center gap-2 rounded-md px-2 text-left text-xs text-slate-300 hover:bg-slate-800 disabled:text-slate-600'
const chartTypes: Array<{ value: ChartType; label: string }> = [{ value: 'candles', label: 'Candles' }, { value: 'bars', label: 'Bars' }, { value: 'line', label: 'Line' }, { value: 'area', label: 'Area' }]
const colors = ['#60a5fa', '#f59e0b', '#a78bfa', '#22d3ee', '#f472b6']

export function DatasetChart({ workspaceNavigation }: { workspaceNavigation?: ReactNode } = {}) {
  const market = useMarket()!
  const [importing, setImporting] = useState(false), [deleting, setDeleting] = useState(false), [settingsOpen, setSettingsOpen] = useState(false)
  const [timeframe, setTimeframe] = useState<Timeframe>('1h')
  const [openMenu, setOpenMenu] = useState<'timeframe' | 'type' | 'layout' | 'indicators' | null>(null)
  const [settings, setSettings] = useState<ChartSettings>(defaultChartSettings)
  const [indicators, setIndicators] = useState<IndicatorConfig[]>([])
  const [tool, setTool] = useState<DrawingTool>('cursor'), [drawings, setDrawings] = useState<Drawing[]>([]), [selectedDrawing, setSelectedDrawing] = useState<string | null>(null)
  const [past, setPast] = useState<Drawing[][]>([]), [future, setFuture] = useState<Drawing[][]>([])
  const blocked = market.busy || market.uncertain
  const selected = market.selected, page = market.page
  useEffect(() => {
    const native = normalizeTimeframe(selected?.timeframe ?? '')
    if (native) setTimeframe(native)
    setDrawings([]); setPast([]); setFuture([]); setSelectedDrawing(null); setTool('cursor')
  }, [selected?.id, selected?.timeframe])
  const availability = timeframeAvailability(selected?.timeframe ?? '')
  const displayItems = useMemo(() => page && selected ? aggregateCandles(page.items, selected.timeframe, timeframe) : [], [page, selected, timeframe])
  const displayPage = page ? { dataset: page.dataset, items: displayItems } : null
  const commitDrawings = (next: Drawing[]) => { setPast(previous => [...previous.slice(-39), drawings]); setDrawings(next); setFuture([]) }
  const addIndicator = (type: IndicatorConfig['type']) => setIndicators(previous => [...previous, { id: `${type}-${Date.now()}-${previous.length}`, type, period: type === 'rsi' ? 14 : type === 'ema' ? 20 : 50, color: colors[previous.length % colors.length] }])

  return <section aria-label="Chart" data-testid="chart-view" className="flex h-full min-h-0 flex-col overflow-hidden">
    <div data-testid="chart-toolbar" className="flex min-h-10 shrink-0 flex-wrap items-center gap-1 overflow-visible border-b border-slate-800 bg-slate-925 px-2 py-1 sm:flex-nowrap">
      <label className="flex h-8 min-w-[150px] max-w-72 items-center gap-1.5 text-[10px] font-medium text-slate-600">Dataset<select aria-label="Dataset" className="h-8 min-w-0 flex-1 rounded-md border border-slate-800 bg-slate-950 px-2 text-xs font-medium text-slate-200 outline-none focus:border-slate-600" value={selected?.id ?? ''} disabled={blocked} onChange={event => { const item = market.items.find(value => value.id === event.target.value); if (item) market.select(item) }}>
        <option value="" disabled>Select a dataset</option>{selected && !market.items.some(item => item.id === selected.id) && <option value={selected.id}>{selected.name}</option>}{market.items.map(item => <option key={item.id} value={item.id}>{item.symbol} · {item.name}</option>)}
      </select></label>
      <details open={openMenu === 'timeframe'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('timeframe'); else if (openMenu === 'timeframe') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Timeframe" title="Timeframe" className="flex h-8 min-w-12 list-none cursor-pointer items-center justify-center rounded-md px-2 text-xs font-semibold text-slate-300 hover:bg-slate-800">{timeframeLabel(timeframe)}<Icon name="chevron" className="ml-1 h-3 w-3" /></summary><div className={menuPanel}><p className="px-2 pb-1 text-[10px] uppercase tracking-wider text-slate-600">Display interval</p>{availability.map(option => <button key={option.value} type="button" disabled={!option.enabled || !selected} title={option.reason} className={`${menuRow} ${timeframe === option.value ? 'bg-slate-800 text-white' : ''}`} onClick={() => { setTimeframe(option.value); setOpenMenu(null) }}><span className="w-8 font-mono">{timeframeLabel(option.value)}</span><span className="ml-auto text-[9px] text-slate-600">{option.value === normalizeTimeframe(selected?.timeframe ?? '') ? 'Native' : option.enabled ? 'UTC' : 'Unavailable'}</span></button>)}</div></details>
      <details open={openMenu === 'type'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('type'); else if (openMenu === 'type') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Chart type" title="Chart type" className={iconButton}><Icon name="candle" className="h-4 w-4" /></summary><div className={menuPanel}>{chartTypes.map(option => <button key={option.value} type="button" className={`${menuRow} ${settings.chartType === option.value ? 'bg-slate-800 text-white' : ''}`} onClick={() => { setSettings(value => ({ ...value, chartType: option.value })); setOpenMenu(null) }}>{option.label}{settings.chartType === option.value && <span className="ml-auto">✓</span>}</button>)}<div className="my-1 border-t border-slate-800"/><button disabled title="Requires bid/ask and order-flow data" className={menuRow}>Footprint <span className="ml-auto text-[9px]">enriched data</span></button><button disabled title="Requires volume-at-price data" className={menuRow}>TPO <span className="ml-auto text-[9px]">enriched data</span></button></div></details>
      <details open={openMenu === 'layout'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('layout'); else if (openMenu === 'layout') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Chart layout" title="Chart layout" className={iconButton}><Icon name="layout" className="h-4 w-4" /></summary><div className={menuPanel}><button type="button" onClick={() => setOpenMenu(null)} className={`${menuRow} bg-slate-800 text-white`}><Icon name="workspace" className="h-4 w-4"/>Single chart<span className="ml-auto">✓</span></button><button disabled title="Multi-chart workspaces are not available yet" className={menuRow}><Icon name="layout" className="h-4 w-4"/>Two charts<span className="ml-auto text-[9px]">Soon</span></button><button disabled title="Additional layouts are not available yet" className={menuRow}><Icon name="more" className="h-4 w-4"/>More layouts<span className="ml-auto text-[9px]">Soon</span></button></div></details>
      <details open={openMenu === 'indicators'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('indicators'); else if (openMenu === 'indicators') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Indicators" title="Indicators" className={`${iconButton} ${indicators.length ? 'text-slate-200' : ''}`}><Icon name="indicator" className="h-4 w-4" /></summary><div className={`${menuPanel} w-64`}><p className="px-2 pb-1 text-[10px] uppercase tracking-wider text-slate-600">Visual indicators</p><div className="grid grid-cols-3 gap-1">{(['sma', 'ema', 'rsi'] as const).map(type => <button key={type} className="min-h-8 rounded-md border border-slate-700 px-2 text-[10px] font-semibold uppercase text-slate-300 hover:bg-slate-800" onClick={() => addIndicator(type)}>+ {type}</button>)}</div>{indicators.map(indicator => <div key={indicator.id} className="mt-1 flex items-center gap-1 rounded-md bg-slate-950 p-1.5"><span style={{ color: indicator.color }} className="w-8 text-[10px] font-bold uppercase">{indicator.type}</span><input aria-label={`${indicator.type.toUpperCase()} period`} type="number" min="2" max="200" value={indicator.period} onChange={event => setIndicators(items => items.map(item => item.id === indicator.id ? { ...item, period: Math.max(2, Math.min(200, Number(event.target.value) || 2)) } : item))} className="h-7 min-w-0 flex-1 rounded border border-slate-700 bg-slate-900 px-1 text-xs text-slate-200"/><button aria-label={`Remove ${indicator.type.toUpperCase()}`} title="Remove indicator" className={iconButton} onClick={() => setIndicators(items => items.filter(item => item.id !== indicator.id))}><Icon name="close" className="h-3.5 w-3.5"/></button></div>)}{!indicators.length && <p className="px-2 py-3 text-[10px] leading-4 text-slate-600">Calculated locally from visible closes. Display only.</p>}</div></details>
      <button aria-label="Import CSV" className="flex h-8 shrink-0 items-center gap-1.5 rounded-md border border-slate-700 bg-slate-800 px-2 text-[11px] font-semibold text-slate-200 transition hover:bg-slate-700 disabled:opacity-40" disabled={blocked} onClick={() => setImporting(true)}><Icon name="upload" className="h-3.5 w-3.5" /><span aria-hidden="true" className="hidden lg:inline">Import CSV</span><span aria-hidden="true" className="lg:hidden">Import</span></button>
      {market.nextCursor && <button aria-label="More datasets" title="More datasets" className={iconButton} disabled={market.listLoading || blocked} onClick={() => void market.loadList(true)}><Icon name="more" className="h-4 w-4" /></button>}
      <span className="mx-1 h-5 w-px shrink-0 bg-slate-800" aria-hidden="true"/>{workspaceNavigation}
      <ChartUtilities hasChart={!!page} refreshing={market.listLoading} onRefresh={() => void market.loadList()} />
    </div>
    <div className="flex min-h-0 flex-1 flex-col sm:flex-row">
      <ChartToolsRail selected={tool} onSelect={setTool} canUndo={past.length > 0} canRedo={future.length > 0} canDelete={!!selectedDrawing} hasDrawings={drawings.length > 0} onUndo={() => { const previous = past.at(-1); if (!previous) return; setFuture(items => [drawings, ...items]); setDrawings(previous); setPast(items => items.slice(0, -1)); setSelectedDrawing(null) }} onRedo={() => { const next = future[0]; if (!next) return; setPast(items => [...items, drawings]); setDrawings(next); setFuture(items => items.slice(1)); setSelectedDrawing(null) }} onDelete={() => { if (selectedDrawing) { commitDrawings(drawings.filter(item => item.id !== selectedDrawing)); setSelectedDrawing(null) } }} onClear={() => { commitDrawings([]); setSelectedDrawing(null) }} />
      <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto p-2.5 sm:p-3">
      {market.listLoading && <p role="status" className="text-xs text-slate-400">Loading datasets…</p>}{market.listError && <p role="alert" className="text-sm text-rose-300">{market.listError}</p>}{market.notice && <p role="status" className="text-xs text-emerald-300">{market.notice}</p>}{market.mutationError && !importing && <p role="alert" className="text-sm text-rose-300">{market.mutationError}</p>}{market.uncertain && !importing && <button className={buttonClass} disabled={market.busy} onClick={() => void market.importData()}>Retry import</button>}
      {!selected && !market.listLoading && <div className="my-auto py-10 text-center"><span className="sr-only">Your market datasets</span><div className="mx-auto mb-3 grid h-9 w-9 place-items-center rounded-lg border border-slate-800 bg-slate-925 text-slate-600"><Icon name="chart" className="h-4 w-4" /></div><h2 className="text-sm font-semibold text-slate-200">No market data</h2><p className="mt-1 text-xs text-slate-600">{market.items.length ? 'Select a dataset to begin.' : 'Import an OHLCV dataset to begin.'}</p><button className="mt-4 min-h-9 rounded-md border border-slate-700 bg-slate-800 px-3 text-xs font-semibold text-slate-200 hover:bg-slate-700" disabled={blocked} onClick={() => setImporting(true)}>Import CSV</button></div>}
      {selected && <><div className="flex flex-wrap items-center justify-between gap-2"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate text-sm font-semibold text-slate-100">{selected.name}</h2><span className="shrink-0 text-[10px] font-medium text-slate-500">{selected.symbol}</span></div><p className="mt-0.5 text-[10px] text-slate-600">{timeframeLabel(timeframe)} display · {displayItems.length} visible · {selected.timeframe} native · UTC</p></div><details className="relative"><summary aria-label="Dataset details" title="Dataset details" className={`${iconButton} list-none cursor-pointer`}><Icon name="more" className="h-4 w-4"/></summary><div className="absolute right-0 top-9 z-30 w-64 rounded-lg border border-slate-700 bg-slate-900 p-2 text-[10px] text-slate-500 shadow-2xl"><p className="break-words text-slate-300">{selected.sourceKind === 'SYNTHETIC' ? 'Synthetic · not market prices' : 'User upload · source unverified'}</p><p className="mt-1 break-words">{selected.sourceLabel}</p><button className="mt-2 min-h-8 w-full rounded-md px-2 text-left text-xs text-red-300 hover:bg-red-400/10" disabled={blocked} onClick={() => setDeleting(true)}>Delete dataset</button></div></details></div>
        {selected.gapCount > 0 && <p role="note" className="border-l-2 border-amber-400 pl-3 text-xs text-amber-200">{selected.gapCount} missing candle intervals. No candles were filled; gap-free backtests must reject this dataset.</p>}
        <div className="flex flex-wrap items-center gap-1.5 text-[10px] text-slate-500"><label className="flex items-center gap-1">Window<select aria-label="Candle window" value={market.window} disabled={blocked} className="h-7 rounded border border-slate-800 bg-slate-900 px-1.5 text-slate-200" onChange={event => market.setWindow(Number(event.target.value))}>{[50, 100, 200].map(size => <option key={size} value={size}>{size} bars</option>)}</select></label><button className={buttonClass} disabled={blocked || market.pageLoading || !page || page.start === 0} onClick={() => void market.loadPage(Math.max(0, page!.start - market.window))}>Older candles</button><button className={buttonClass} disabled={blocked || market.pageLoading || !page || page.start + page.items.length >= page.total} onClick={() => void market.loadPage(page!.start + market.window)}>Newer candles</button>{page && <span>{page.start + (page.items.length ? 1 : 0)}–{page.start + page.items.length} / {page.total}</span>}<span className="ml-auto">Drawings stay in this session only</span></div>
        {market.pageLoading && <p role="status" className="py-8 text-sm text-slate-400">Loading candles…</p>}{market.pageError && <div><p role="alert" className="text-sm text-rose-300">{market.pageError}</p><button className={buttonClass} onClick={() => void market.loadPage()}>Retry candles</button></div>}
        {displayPage && <><div data-chart-export><CandleChart key={`${page!.dataset.id}:${page!.start}:${page!.items.length}:${timeframe}`} page={displayPage} settings={settings} indicators={indicators} activeTool={tool} drawings={drawings} selectedDrawingId={selectedDrawing} onSelectDrawing={setSelectedDrawing} onAddDrawing={drawing => { commitDrawings([...drawings, drawing]); setSelectedDrawing(drawing.id); setTool('cursor') }} /></div><div className="flex items-center justify-end gap-1">{selectedDrawing && drawings.find(item => item.id === selectedDrawing)?.type === 'text' && <input aria-label="Selected note text" maxLength={80} value={drawings.find(item => item.id === selectedDrawing)?.text ?? ''} onChange={event => setDrawings(items => items.map(item => item.id === selectedDrawing ? { ...item, text: event.target.value } : item))} onBlur={() => { setPast(items => [...items.slice(-39), drawings]); setFuture([]) }} className="h-8 max-w-52 rounded-md border border-slate-700 bg-slate-900 px-2 text-xs text-slate-200"/>}<button aria-label="Chart settings" title="Chart settings" className={iconButton} onClick={() => setSettingsOpen(true)}><Icon name="settings" className="h-4 w-4"/></button></div></>}
        <details className="shrink-0 border-t border-slate-800 pt-1 text-[10px] text-slate-600"><summary className="cursor-pointer py-1">Provenance</summary><dl className="space-y-1 break-all py-2"><dt>Date range · UTC</dt><dd>{selected.firstTime} → {selected.lastTime}</dd><dt>Canonical OHLCV SHA-256</dt><dd>{selected.dataHash}</dd><dt>Original CSV SHA-256</dt><dd>{selected.rawHash}</dd><dt>Format</dt><dd>{selected.formatVersion} · fingerprints do not verify source authenticity</dd></dl></details></>}
      </div>
    </div>
    <Modal open={settingsOpen} label="Chart settings" onClose={() => setSettingsOpen(false)}><ChartSettingsPanel value={settings} onChange={setSettings} onClose={() => setSettingsOpen(false)} /></Modal>
    <Modal open={importing} label="Import market data" onClose={() => { if (!blocked) setImporting(false) }}><ImportForm onClose={() => setImporting(false)} onComplete={() => setImporting(false)} /></Modal>
    <Modal open={deleting} label="Delete dataset" onClose={() => { if (!market.busy) setDeleting(false) }}><div className="mx-auto w-[min(420px,92vw)] space-y-4 border border-slate-700 bg-slate-950 p-5 text-slate-100"><h2 className="text-lg font-semibold">Delete dataset?</h2><p className="break-words text-sm text-slate-400">Permanently delete {selected?.name} and its candles from your account?</p>{market.mutationError && <p role="alert" className="text-sm text-rose-300">{market.mutationError}</p>}<div className="flex gap-3"><button className={buttonClass} disabled={market.busy} onClick={() => setDeleting(false)}>Cancel deletion</button><button className={buttonClass} disabled={market.busy} onClick={async () => { if (await market.remove()) setDeleting(false) }}>Confirm deletion</button></div></div></Modal>
  </section>
}

function ChartSettingsPanel({ value, onChange, onClose }: { value: ChartSettings; onChange: (value: ChartSettings) => void; onClose: () => void }) {
  const set = <K extends keyof ChartSettings>(key: K, next: ChartSettings[K]) => onChange({ ...value, [key]: next })
  const toggles: Array<[keyof Pick<ChartSettings, 'showSymbol' | 'showOhlc' | 'showVolume' | 'showPriceLine' | 'showGrid' | 'candleBorders' | 'candleWicks'>, string]> = [['showSymbol', 'Symbol'], ['showOhlc', 'OHLC'], ['showVolume', 'Volume'], ['showPriceLine', 'Last price line'], ['showGrid', 'Grid'], ['candleBorders', 'Candle borders'], ['candleWicks', 'Candle wicks']]
  return <div className="m-auto max-h-[88vh] w-[min(520px,94vw)] overflow-y-auto rounded-xl border border-slate-700 bg-slate-950 p-5 text-slate-200 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-base font-semibold">Chart settings</h2><p className="mt-1 text-[11px] text-slate-600">Local display · UTC</p></div><button aria-label="Close chart settings" className={iconButton} onClick={onClose}><Icon name="close" className="h-4 w-4"/></button></div><div className="grid gap-5 sm:grid-cols-2"><section><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-slate-600">Style</h3><label className="text-xs text-slate-400">Chart type<select aria-label="Settings chart type" value={value.chartType} onChange={event => set('chartType', event.target.value as ChartType)} className="mt-1 h-9 w-full rounded-md border border-slate-700 bg-slate-900 px-2 text-slate-200">{chartTypes.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="mt-3 block text-xs text-slate-400">Candle spacing<input aria-label="Candle spacing" type="range" min="20" max="100" value={value.spacing} onChange={event => set('spacing', Number(event.target.value))} className="mt-2 w-full"/></label><div className="mt-3 grid grid-cols-2 gap-2">{([['bullColor', 'Bull'], ['bearColor', 'Bear'], ['background', 'Background'], ['gridColor', 'Grid']] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-md border border-slate-800 p-2 text-[11px] text-slate-400">{label}<input aria-label={`${label} color`} type="color" value={value[key]} onChange={event => set(key, event.target.value)} className="h-6 w-8 border-0 bg-transparent"/></label>)}</div></section><section><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-slate-600">Visible</h3><div className="space-y-1">{toggles.map(([key, label]) => <label key={key} className="flex min-h-9 items-center justify-between rounded-md px-2 text-xs text-slate-300 hover:bg-slate-900">{label}<input type="checkbox" checked={value[key]} onChange={event => set(key, event.target.checked)} /></label>)}</div><div className="mt-3 flex min-h-9 items-center justify-between rounded-md border border-slate-800 px-2 text-xs text-slate-400"><span>Timezone</span><span className="font-mono text-slate-200">UTC</span></div></section></div></div>
}
