import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { buttonClass } from '../auth/AuthForm'
import { Modal } from '../components/Modal'
import { ChartToolsRail, ChartUtilities } from '../components/ChartControls'
import { Icon } from '../components/Icon'
import { CandleChart } from './CandleChart'
import { aggregateCandles, normalizeTimeframe, timeframeAvailability, timeframeLabel, type Timeframe } from './chartMath'
import { defaultChartSettings, drawingLabels, type ChartSettings, type ChartType, type Drawing, type DrawingTool, type IndicatorConfig, type MagnetMode } from './chartTypes'
import { ImportForm } from './ImportForm'
import { useMarket } from './MarketContext'

const iconButton = 'icon-tool grid h-8 w-8 shrink-0 place-items-center rounded-md text-slate-500 transition hover:bg-slate-800 hover:text-slate-100 focus-visible:ring-2 focus-visible:ring-slate-300 disabled:opacity-35'
const menuPanel = 'absolute left-0 top-9 z-40 min-w-44 rounded-lg border border-slate-700 bg-slate-900 p-1.5 shadow-2xl max-sm:fixed max-sm:left-2 max-sm:right-2 max-sm:top-24 max-sm:w-auto'
const menuRow = 'flex min-h-9 w-full items-center gap-2 rounded-md px-2 text-left text-xs text-slate-300 hover:bg-slate-800 disabled:text-slate-600'
const chartTypes: Array<{ value: ChartType; label: string }> = [{ value: 'candles', label: 'Candles' }, { value: 'bars', label: 'Bars' }, { value: 'line', label: 'Line' }, { value: 'area', label: 'Area' }]
const colors = ['#60a5fa', '#f59e0b', '#a78bfa', '#22d3ee', '#f472b6']

export function DatasetChart({ workspaceNavigation }: { workspaceNavigation?: ReactNode } = {}) {
  const market = useMarket()!
  const [importing, setImporting] = useState(false), [deleting, setDeleting] = useState(false), [settingsOpen, setSettingsOpen] = useState(false)
  const [timeframe, setTimeframe] = useState<Timeframe>('1h')
  const [openMenu, setOpenMenu] = useState<'timeframe' | 'type' | 'layout' | 'indicators' | null>(null)
  const [settings, setSettings] = useState<ChartSettings>(defaultChartSettings)
  const [indicators, setIndicators] = useState<IndicatorConfig[]>([])
  const [tool, setTool] = useState<DrawingTool>('cursor'), [drawings, setDrawings] = useState<Drawing[]>([]), [selectedDrawing, setSelectedDrawing] = useState<string | null>(null)
  const [past, setPast] = useState<Drawing[][]>([]), [future, setFuture] = useState<Drawing[][]>([])
  const [magnet, setMagnet] = useState<MagnetMode>('off'), [stayInMode, setStayInMode] = useState(false), [objectTreeOpen, setObjectTreeOpen] = useState(false)
  const [visibleNotice, setVisibleNotice] = useState<string | null>(null)
  const blocked = market.busy || market.uncertain
  const selected = market.selected, page = market.page
  useEffect(() => {
    const native = normalizeTimeframe(selected?.timeframe ?? '')
    if (native) setTimeframe(native)
    setDrawings([]); setPast([]); setFuture([]); setSelectedDrawing(null); setTool('cursor')
  }, [selected?.id, selected?.timeframe])
  useEffect(() => {
    const shortcuts = (event: KeyboardEvent) => {
      const target = event.target
      if (target instanceof HTMLElement && (['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName) || target.isContentEditable)) return
      if (event.key === 'Escape') setTool('cursor')
      if (!event.altKey) return
      const next: DrawingTool | null = event.key.toLowerCase() === 't' ? 'trend' : event.key.toLowerCase() === 'h' ? 'horizontal' : event.key.toLowerCase() === 'v' ? 'vertical' : null
      if (next) { event.preventDefault(); setTool(next) }
    }
    window.addEventListener('keydown', shortcuts); return () => window.removeEventListener('keydown', shortcuts)
  }, [])
  useEffect(() => {
    if (!market.notice) return
    setVisibleNotice(market.notice)
    const timer = window.setTimeout(() => setVisibleNotice(null), 4000)
    return () => window.clearTimeout(timer)
  }, [market.notice])
  const availability = timeframeAvailability(selected?.timeframe ?? '')
  const displayItems = useMemo(() => page && selected ? aggregateCandles(page.items, selected.timeframe, timeframe) : [], [page, selected, timeframe])
  const displayPage = page ? { dataset: page.dataset, items: displayItems } : null
  const commitDrawings = (next: Drawing[], before = drawings) => { setPast(previous => [...previous.slice(-39), before]); setDrawings(next); setFuture([]) }
  const addIndicator = (type: IndicatorConfig['type']) => setIndicators(previous => [...previous, { id: `${type}-${Date.now()}-${previous.length}`, type, period: type === 'rsi' ? 14 : type === 'ema' ? 20 : 50, color: colors[previous.length % colors.length], visible: true }])
  const undo = () => { const previous = past.at(-1); if (!previous) return; setFuture(items => [drawings, ...items]); setDrawings(previous); setPast(items => items.slice(0, -1)); setSelectedDrawing(null) }
  const redo = () => { const next = future[0]; if (!next) return; setPast(items => [...items, drawings]); setDrawings(next); setFuture(items => items.slice(1)); setSelectedDrawing(null) }
  const deleteSelected = () => {
    if (!selectedDrawing) return
    commitDrawings(drawings.filter(item => item.id !== selectedDrawing)); setSelectedDrawing(null)
  }
  const updateDrawing = (drawing: Drawing) => setDrawings(items => items.map(item => item.id === drawing.id ? drawing : item))
  const commitDrawingEdit = (before: Drawing, after: Drawing) => {
    const snapshot = drawings.map(item => item.id === before.id ? before : item)
    setDrawings(items => items.map(item => item.id === after.id ? after : item)); setPast(items => [...items.slice(-39), snapshot]); setFuture([])
  }

  return <section aria-label="Chart" data-testid="chart-view" className="flex h-full min-h-0 flex-col overflow-hidden">
    <div data-testid="chart-toolbar" className="flex min-h-10 shrink-0 flex-wrap items-center gap-1 overflow-visible border-b border-slate-800 bg-slate-925 px-2 py-1 sm:flex-nowrap">
      <label className="flex h-8 min-w-[150px] max-w-72 items-center gap-1.5 text-[10px] font-medium text-slate-600">Dataset<select aria-label="Dataset" className="h-8 min-w-0 flex-1 rounded-md border border-slate-800 bg-slate-950 px-2 text-xs font-medium text-slate-200 outline-none focus:border-slate-600" value={selected?.id ?? ''} disabled={blocked} onChange={event => { const item = market.items.find(value => value.id === event.target.value); if (item) market.select(item) }}>
        <option value="" disabled>Select a dataset</option>{selected && !market.items.some(item => item.id === selected.id) && <option value={selected.id}>{selected.name}</option>}{market.items.map(item => <option key={item.id} value={item.id}>{item.symbol} · {item.name}</option>)}
      </select></label>
      <span className="hidden max-w-28 truncate px-1.5 font-mono text-[11px] font-semibold text-slate-300 md:inline" title={selected?.symbol ?? 'No symbol'}>{selected?.symbol ?? '—'}</span>
      <details open={openMenu === 'timeframe'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('timeframe'); else if (openMenu === 'timeframe') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Timeframe" title="Timeframe" className="flex h-8 min-w-12 list-none cursor-pointer items-center justify-center rounded-md px-2 text-xs font-semibold text-slate-300 hover:bg-slate-800">{timeframeLabel(timeframe)}<Icon name="chevron" className="ml-1 h-3 w-3" /></summary><div className={menuPanel}><p className="px-2 pb-1 text-[10px] uppercase tracking-wider text-slate-600">Display interval</p>{availability.map(option => <button key={option.value} type="button" disabled={!option.enabled || !selected} title={option.reason} className={`${menuRow} ${timeframe === option.value ? 'bg-slate-800 text-white' : ''}`} onClick={() => { setTimeframe(option.value); setOpenMenu(null) }}><span className="w-8 font-mono">{timeframeLabel(option.value)}</span><span className="ml-auto text-[9px] text-slate-600">{option.value === normalizeTimeframe(selected?.timeframe ?? '') ? 'Native' : option.enabled ? 'UTC' : 'Unavailable'}</span></button>)}</div></details>
      <details open={openMenu === 'type'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('type'); else if (openMenu === 'type') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Chart type" title="Chart type" className={iconButton}><Icon name="candle" className="h-4 w-4" /></summary><div className={menuPanel}>{chartTypes.map(option => <button key={option.value} type="button" className={`${menuRow} ${settings.chartType === option.value ? 'bg-slate-800 text-white' : ''}`} onClick={() => { setSettings(value => ({ ...value, chartType: option.value })); setOpenMenu(null) }}>{option.label}{settings.chartType === option.value && <span className="ml-auto">✓</span>}</button>)}<div className="my-1 border-t border-slate-800"/><button disabled title="Requires bid/ask and order-flow data" className={menuRow}>Footprint <span className="ml-auto text-[9px]">enriched data</span></button><button disabled title="Requires volume-at-price data" className={menuRow}>TPO <span className="ml-auto text-[9px]">enriched data</span></button></div></details>
      <details open={openMenu === 'layout'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('layout'); else if (openMenu === 'layout') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Chart layout" title="Chart layout" className={iconButton}><Icon name="layout" className="h-4 w-4" /></summary><div className={menuPanel}><button type="button" onClick={() => setOpenMenu(null)} className={`${menuRow} bg-slate-800 text-white`}><Icon name="workspace" className="h-4 w-4"/>Single chart<span className="ml-auto">✓</span></button><button disabled title="Multi-chart workspaces are not available yet" className={menuRow}><Icon name="layout" className="h-4 w-4"/>Two charts<span className="ml-auto text-[9px]">Soon</span></button><button disabled title="Additional layouts are not available yet" className={menuRow}><Icon name="more" className="h-4 w-4"/>More layouts<span className="ml-auto text-[9px]">Soon</span></button></div></details>
      <details open={openMenu === 'indicators'} onToggle={event => { if (event.currentTarget.open) setOpenMenu('indicators'); else if (openMenu === 'indicators') setOpenMenu(null) }} className="relative shrink-0"><summary aria-label="Indicators" title="Indicators" className={`${iconButton} ${indicators.length ? 'text-slate-200' : ''}`}><Icon name="indicator" className="h-4 w-4" /></summary><div className={`${menuPanel} w-64`}><p className="px-2 pb-1 text-[10px] uppercase tracking-wider text-slate-600">Visual indicators</p><div className="grid grid-cols-3 gap-1">{(['sma', 'ema', 'rsi'] as const).map(type => <button key={type} className="min-h-8 rounded-md border border-slate-700 px-2 text-[10px] font-semibold uppercase text-slate-300 hover:bg-slate-800" onClick={() => addIndicator(type)}>+ {type}</button>)}</div>{indicators.map(indicator => <div key={indicator.id} className="mt-1 flex items-center gap-1 rounded-md bg-slate-950 p-1.5"><span style={{ color: indicator.color }} className="w-8 text-[10px] font-bold uppercase">{indicator.type}</span><input aria-label={`${indicator.type.toUpperCase()} period`} type="number" min="2" max="200" value={indicator.period} onChange={event => setIndicators(items => items.map(item => item.id === indicator.id ? { ...item, period: Math.max(2, Math.min(200, Number(event.target.value) || 2)) } : item))} className="h-7 min-w-0 flex-1 rounded border border-slate-700 bg-slate-900 px-1 text-xs text-slate-200"/><button aria-label={`Remove ${indicator.type.toUpperCase()}`} title="Remove indicator" className={iconButton} onClick={() => setIndicators(items => items.filter(item => item.id !== indicator.id))}><Icon name="close" className="h-3.5 w-3.5"/></button></div>)}{!indicators.length && <p className="px-2 py-3 text-[10px] leading-4 text-slate-600">Calculated locally from visible closes. Display only.</p>}</div></details>
      <button type="button" disabled={!past.length} aria-label="Undo drawing" title="Undo drawing" data-tooltip="Undo" onClick={undo} className={iconButton}><Icon name="undo" className="h-4 w-4" /></button>
      <button type="button" disabled={!future.length} aria-label="Redo drawing" title="Redo drawing" data-tooltip="Redo" onClick={redo} className={iconButton}><Icon name="redo" className="h-4 w-4" /></button>
      <button aria-label="Import CSV" className="flex h-8 shrink-0 items-center gap-1.5 rounded-md border border-slate-700 bg-slate-800 px-2 text-[11px] font-semibold text-slate-200 transition hover:bg-slate-700 disabled:opacity-40" disabled={blocked} onClick={() => setImporting(true)}><Icon name="upload" className="h-3.5 w-3.5" /><span aria-hidden="true" className="hidden lg:inline">Import CSV</span><span aria-hidden="true" className="lg:hidden">Import</span></button>
      {market.nextCursor && <button aria-label="More datasets" title="More datasets" className={iconButton} disabled={market.listLoading || blocked} onClick={() => void market.loadList(true)}><Icon name="more" className="h-4 w-4" /></button>}
      <span className="mx-1 h-5 w-px shrink-0 bg-slate-800" aria-hidden="true"/>{workspaceNavigation}
      <ChartUtilities hasChart={!!page} refreshing={market.listLoading} onRefresh={() => void market.loadList()} />
    </div>
    <div className="flex min-h-0 flex-1 flex-col sm:flex-row">
      <ChartToolsRail selected={tool} onSelect={setTool} canDelete={!!selectedDrawing} hasDrawings={drawings.length > 0} onDelete={deleteSelected} onClear={() => { commitDrawings([]); setSelectedDrawing(null) }} magnet={magnet} onMagnetChange={setMagnet} stayInMode={stayInMode} onToggleStay={() => setStayInMode(value => !value)} onObjectTree={() => setObjectTreeOpen(value => !value)} />
      <div className="relative flex min-h-0 flex-1 flex-col gap-1.5 overflow-x-hidden overflow-y-auto p-2 sm:p-2.5">
      {market.listLoading && <p role="status" className="text-xs text-slate-400">Loading datasets…</p>}{market.listError && <p role="alert" className="text-sm text-rose-300">{market.listError}</p>}{visibleNotice && <p role="status" className="absolute right-4 top-3 z-40 rounded-md border border-emerald-400/20 bg-slate-900/95 px-2.5 py-1.5 text-[10px] text-emerald-300 shadow-xl">{visibleNotice}</p>}{market.mutationError && !importing && <p role="alert" className="text-sm text-rose-300">{market.mutationError}</p>}{market.uncertain && !importing && <button className={buttonClass} disabled={market.busy} onClick={() => void market.importData()}>Retry import</button>}
      {!selected && !market.listLoading && <div className="my-auto py-10 text-center"><span className="sr-only">Your market datasets</span><div className="mx-auto mb-3 grid h-9 w-9 place-items-center rounded-lg border border-slate-800 bg-slate-925 text-slate-600"><Icon name="chart" className="h-4 w-4" /></div><h2 className="text-sm font-semibold text-slate-200">No market data</h2><p className="mt-1 text-xs text-slate-600">{market.items.length ? 'Select a dataset to begin.' : 'Import an OHLCV dataset to begin.'}</p><button className="mt-4 min-h-9 rounded-md border border-slate-700 bg-slate-800 px-3 text-xs font-semibold text-slate-200 hover:bg-slate-700" disabled={blocked} onClick={() => setImporting(true)}>Import CSV</button></div>}
      {selected && <><h2 className="sr-only">{selected.name}</h2>
        {selected.gapCount > 0 && <p role="note" className="border-l-2 border-amber-400 pl-3 text-xs text-amber-200">{selected.gapCount} missing candle intervals. No candles were filled; gap-free backtests must reject this dataset.</p>}
        <div className="flex min-h-8 flex-wrap items-center gap-1 text-[10px] text-slate-500"><span className="mr-1 max-w-48 truncate font-medium text-slate-300">{selected.name}</span><label className="flex items-center gap-1">Window<select aria-label="Candle window" value={market.window} disabled={blocked} className="h-7 rounded border border-slate-800 bg-slate-900 px-1.5 text-slate-200" onChange={event => market.setWindow(Number(event.target.value))}>{[50, 100, 200].map(size => <option key={size} value={size}>{size} bars</option>)}</select></label><button className="h-7 rounded border border-slate-700 bg-slate-800 px-2 text-[10px] font-medium text-slate-300 hover:bg-slate-700 disabled:opacity-35" disabled={blocked || market.pageLoading || !page || page.start === 0} onClick={() => void market.loadPage(Math.max(0, page!.start - market.window))}>Older</button><button className="h-7 rounded border border-slate-700 bg-slate-800 px-2 text-[10px] font-medium text-slate-300 hover:bg-slate-700 disabled:opacity-35" disabled={blocked || market.pageLoading || !page || page.start + page.items.length >= page.total} onClick={() => void market.loadPage(page!.start + market.window)}>Newer</button>{page && <span>{page.start + (page.items.length ? 1 : 0)}–{page.start + page.items.length} / {page.total}</span>}<details className="relative ml-auto"><summary aria-label="Dataset details" title="Dataset details" className={`${iconButton} list-none cursor-pointer`}><Icon name="more" className="h-4 w-4"/></summary><div className="absolute right-0 top-9 z-30 w-64 rounded-lg border border-slate-700 bg-slate-900 p-2 text-[10px] text-slate-500 shadow-2xl"><p className="break-words text-slate-300">{selected.sourceKind === 'SYNTHETIC' ? 'Synthetic · not market prices' : 'User upload · source unverified'}</p><p className="mt-1 break-words">{selected.sourceLabel}</p><button className="mt-2 min-h-8 w-full rounded-md px-2 text-left text-xs text-red-300 hover:bg-red-400/10" disabled={blocked} onClick={() => setDeleting(true)}>Delete dataset</button></div></details></div>
        {market.pageLoading && <p role="status" className="py-8 text-sm text-slate-400">Loading candles…</p>}{market.pageError && <div><p role="alert" className="text-sm text-rose-300">{market.pageError}</p><button className={buttonClass} onClick={() => void market.loadPage()}>Retry candles</button></div>}
        {displayPage && <div className="relative min-h-0" data-chart-export><CandleChart key={`${page!.dataset.id}:${page!.start}:${page!.items.length}:${timeframe}`} page={displayPage} settings={settings} indicators={indicators} activeTool={tool} drawings={drawings} selectedDrawingId={selectedDrawing} magnet={magnet} stayInMode={stayInMode} onSelectDrawing={setSelectedDrawing} onDeleteSelected={deleteSelected} onUndo={undo} onRedo={redo} onCancelTool={() => setTool('cursor')} onUpdateDrawing={updateDrawing} onCommitDrawingEdit={commitDrawingEdit} onToggleIndicator={id => setIndicators(items => items.map(item => item.id === id ? { ...item, visible: !item.visible } : item))} onRemoveIndicator={id => setIndicators(items => items.filter(item => item.id !== id))} onAddDrawing={drawing => { commitDrawings([...drawings, drawing]); setSelectedDrawing(drawing.id) }} />{objectTreeOpen && <ObjectTree drawings={drawings} indicators={indicators} selected={selectedDrawing} onSelect={setSelectedDrawing} onClose={() => setObjectTreeOpen(false)} onDrawingsChange={next => commitDrawings(next)} onIndicatorsChange={setIndicators}/>}<ChartClock timezone={settings.timezone} onTimezoneChange={timezone => setSettings(value => ({ ...value, timezone }))}/>{selectedDrawing && ['text', 'note', 'callout'].includes(drawings.find(item => item.id === selectedDrawing)?.type ?? '') && <input aria-label="Selected note text" maxLength={80} value={drawings.find(item => item.id === selectedDrawing)?.text ?? ''} onChange={event => setDrawings(items => items.map(item => item.id === selectedDrawing ? { ...item, text: event.target.value } : item))} className="absolute right-2 top-2 z-30 h-8 max-w-52 rounded-md border border-slate-700 bg-slate-900 px-2 text-xs text-slate-200"/>}<button aria-label="Chart settings" title="Chart settings" data-tooltip="Settings" className={`${iconButton} absolute bottom-2 right-[112px] z-20`} onClick={() => setSettingsOpen(true)}><Icon name="settings" className="h-4 w-4"/></button></div>}
        <details className="shrink-0 border-t border-slate-800 pt-1 text-[10px] text-slate-600"><summary className="cursor-pointer py-1">Provenance</summary><dl className="space-y-1 break-all py-2"><dt>Date range · UTC</dt><dd>{selected.firstTime} → {selected.lastTime}</dd><dt>Canonical OHLCV SHA-256</dt><dd>{selected.dataHash}</dd><dt>Original CSV SHA-256</dt><dd>{selected.rawHash}</dd><dt>Format</dt><dd>{selected.formatVersion} · fingerprints do not verify source authenticity</dd></dl></details></>}
      </div>
    </div>
    <Modal open={settingsOpen} label="Chart settings" onClose={() => setSettingsOpen(false)}><ChartSettingsPanel value={settings} onChange={setSettings} onClose={() => setSettingsOpen(false)} /></Modal>
    <Modal open={importing} label="Import market data" onClose={() => { if (!blocked) setImporting(false) }}><ImportForm onClose={() => setImporting(false)} onComplete={() => setImporting(false)} /></Modal>
    <Modal open={deleting} label="Delete dataset" onClose={() => { if (!market.busy) setDeleting(false) }}><div className="mx-auto w-[min(420px,92vw)] space-y-4 border border-slate-700 bg-slate-950 p-5 text-slate-100"><h2 className="text-lg font-semibold">Delete dataset?</h2><p className="break-words text-sm text-slate-400">Permanently delete {selected?.name} and its candles from your account?</p>{market.mutationError && <p role="alert" className="text-sm text-rose-300">{market.mutationError}</p>}<div className="flex gap-3"><button className={buttonClass} disabled={market.busy} onClick={() => setDeleting(false)}>Cancel deletion</button><button className={buttonClass} disabled={market.busy} onClick={async () => { if (await market.remove()) setDeleting(false) }}>Confirm deletion</button></div></div></Modal>
  </section>
}

function ChartSettingsPanel({ value, onChange, onClose }: { value: ChartSettings; onChange: (value: ChartSettings) => void; onClose: () => void }) {
  const set = <K extends keyof ChartSettings>(key: K, next: ChartSettings[K]) => onChange({ ...value, [key]: next })
  const toggles: Array<[keyof Pick<ChartSettings, 'showSymbol' | 'showOhlc' | 'showVolume' | 'showPriceLine' | 'showLastValue' | 'showGrid' | 'showCrosshair' | 'candleBorders' | 'candleWicks'>, string]> = [['showSymbol', 'Symbol'], ['showOhlc', 'OHLC'], ['showVolume', 'Volume'], ['showPriceLine', 'Last price line'], ['showLastValue', 'Last value label'], ['showGrid', 'Grid'], ['showCrosshair', 'Crosshair'], ['candleBorders', 'Candle borders'], ['candleWicks', 'Candle wicks']]
  return <div className="m-auto max-h-[88vh] w-[min(520px,94vw)] overflow-y-auto rounded-xl border border-slate-700 bg-slate-950 p-5 text-slate-200 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-base font-semibold">Chart settings</h2><p className="mt-1 text-[11px] text-slate-600">Local display · source remains UTC</p></div><button aria-label="Close chart settings" className={iconButton} onClick={onClose}><Icon name="close" className="h-4 w-4"/></button></div><div className="grid gap-5 sm:grid-cols-2"><section><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-slate-600">Style</h3><label className="text-xs text-slate-400">Chart type<select aria-label="Settings chart type" value={value.chartType} onChange={event => set('chartType', event.target.value as ChartType)} className="mt-1 h-9 w-full rounded-md border border-slate-700 bg-slate-900 px-2 text-slate-200">{chartTypes.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="mt-3 block text-xs text-slate-400">Candle spacing<input aria-label="Candle spacing" type="range" min="20" max="100" value={value.spacing} onChange={event => set('spacing', Number(event.target.value))} className="mt-2 w-full"/></label><div className="mt-3 grid grid-cols-2 gap-2">{([['bullColor', 'Bull'], ['bearColor', 'Bear'], ['background', 'Background'], ['gridColor', 'Grid']] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-md border border-slate-800 p-2 text-[11px] text-slate-400">{label}<input aria-label={`${label} color`} type="color" value={value[key]} onChange={event => set(key, event.target.value)} className="h-6 w-8 border-0 bg-transparent"/></label>)}</div></section><section><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-slate-600">Visible</h3><div className="space-y-1">{toggles.map(([key, label]) => <label key={key} className="flex min-h-9 items-center justify-between rounded-md px-2 text-xs text-slate-300 hover:bg-slate-900">{label}<input type="checkbox" checked={value[key]} onChange={event => set(key, event.target.checked)} /></label>)}</div><label className="mt-3 block text-xs text-slate-400">Timezone<select aria-label="Chart timezone" value={value.timezone} onChange={event => set('timezone', event.target.value as ChartSettings['timezone'])} className="mt-1 h-9 w-full rounded-md border border-slate-800 bg-slate-900 px-2 font-mono text-[11px] text-slate-200"><option value="UTC">UTC</option><option value="Asia/Ho_Chi_Minh">Asia/Ho_Chi_Minh</option><option value="America/New_York">America/New_York</option><option value="Europe/London">Europe/London</option></select></label></section></div></div>
}

function ObjectTree({ drawings, indicators, selected, onSelect, onClose, onDrawingsChange, onIndicatorsChange }: {
  drawings: Drawing[]; indicators: IndicatorConfig[]; selected: string | null
  onSelect: (id: string | null) => void; onClose: () => void; onDrawingsChange: (items: Drawing[]) => void; onIndicatorsChange: (items: IndicatorConfig[]) => void
}) {
  return <aside aria-label="Object tree" className="absolute right-3 top-3 z-30 w-64 overflow-hidden rounded-lg border border-slate-700 bg-slate-900/95 shadow-2xl backdrop-blur-sm">
    <header className="flex h-9 items-center border-b border-slate-800 px-2.5"><span className="text-[10px] font-semibold uppercase tracking-[.13em] text-slate-400">Object tree</span><button aria-label="Close object tree" className={`${iconButton} ml-auto h-7 w-7`} onClick={onClose}><Icon name="close" className="h-3.5 w-3.5"/></button></header>
    <div className="max-h-72 overflow-y-auto p-1.5">
      {!!indicators.length && <p className="px-2 py-1 text-[9px] uppercase tracking-wider text-slate-600">Indicators</p>}
      {indicators.map(indicator => <div key={indicator.id} className="flex min-h-8 items-center gap-2 rounded-md px-2 text-[11px] text-slate-300 hover:bg-slate-800"><span className="h-1.5 w-1.5 rounded-full" style={{ background: indicator.color }}/><span className="uppercase">{indicator.type} {indicator.period}</span><button aria-label={`${indicator.visible ? 'Hide' : 'Show'} ${indicator.type}`} title={indicator.visible ? 'Hide' : 'Show'} className="ml-auto text-slate-500 hover:text-white" onClick={() => onIndicatorsChange(indicators.map(item => item.id === indicator.id ? { ...item, visible: !item.visible } : item))}><Icon name={indicator.visible ? 'eye' : 'eyeOff'} className="h-3.5 w-3.5"/></button><button aria-label={`Remove ${indicator.type}`} title="Remove" className="text-slate-500 hover:text-red-300" onClick={() => onIndicatorsChange(indicators.filter(item => item.id !== indicator.id))}><Icon name="close" className="h-3.5 w-3.5"/></button></div>)}
      {!!drawings.length && <p className="mt-1 border-t border-slate-800 px-2 pb-1 pt-2 text-[9px] uppercase tracking-wider text-slate-600">Drawings</p>}
      {drawings.map((drawing, index) => <div key={drawing.id} className={`flex min-h-8 items-center gap-1.5 rounded-md px-2 text-[11px] hover:bg-slate-800 ${selected === drawing.id ? 'bg-slate-800 text-white' : 'text-slate-300'}`}>
        <input aria-label={`Rename ${drawingLabels[drawing.type]}`} title="Rename drawing" maxLength={40} value={drawing.name ?? `${drawingLabels[drawing.type]} ${index + 1}`} onFocus={() => onSelect(drawing.id)} onChange={event => onDrawingsChange(drawings.map(item => item.id === drawing.id ? { ...item, name: event.target.value } : item))} className="h-6 min-w-0 flex-1 border-0 bg-transparent px-0.5 text-[10px] text-inherit outline-none"/>
        <button aria-label={`${drawing.locked ? 'Unlock' : 'Lock'} ${drawingLabels[drawing.type]}`} title={drawing.locked ? 'Unlock' : 'Lock'} className="text-slate-500 hover:text-white" onClick={() => onDrawingsChange(drawings.map(item => item.id === drawing.id ? { ...item, locked: !item.locked } : item))}><Icon name={drawing.locked ? 'lock' : 'unlock'} className="h-3.5 w-3.5"/></button>
        <button aria-label={`${drawing.visible === false ? 'Show' : 'Hide'} ${drawingLabels[drawing.type]}`} title={drawing.visible === false ? 'Show' : 'Hide'} className="text-slate-500 hover:text-white" onClick={() => onDrawingsChange(drawings.map(item => item.id === drawing.id ? { ...item, visible: item.visible === false } : item))}><Icon name={drawing.visible === false ? 'eyeOff' : 'eye'} className="h-3.5 w-3.5"/></button>
        <button aria-label={`Remove ${drawingLabels[drawing.type]}`} title="Remove" className="text-slate-500 hover:text-red-300" onClick={() => { onDrawingsChange(drawings.filter(item => item.id !== drawing.id)); if (selected === drawing.id) onSelect(null) }}><Icon name="close" className="h-3.5 w-3.5"/></button>
      </div>)}
      {!indicators.length && !drawings.length && <p className="px-2 py-6 text-center text-[11px] text-slate-600">No chart objects</p>}
    </div>
  </aside>
}

const timezones: ChartSettings['timezone'][] = ['UTC', 'Asia/Ho_Chi_Minh', 'America/New_York', 'Europe/London']

function ChartClock({ timezone, onTimezoneChange }: { timezone: ChartSettings['timezone']; onTimezoneChange: (timezone: ChartSettings['timezone']) => void }) {
  const [now, setNow] = useState(() => new Date())
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer) }, [])
  const label = new Intl.DateTimeFormat('en-GB', { timeZone: timezone, hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).format(now)
  return <details className="absolute bottom-2 right-2 z-20"><summary aria-label="Chart timezone and current time" title="Timezone and current time" className="flex h-7 list-none cursor-pointer items-center gap-1.5 rounded border border-slate-700 bg-slate-900/90 px-2 font-mono text-[9px] text-slate-400 hover:text-white"><Icon name="clock" className="h-3 w-3"/>{label}<span className="text-slate-600">{timezone === 'Asia/Ho_Chi_Minh' ? 'ICT' : timezone === 'America/New_York' ? 'NY' : timezone === 'Europe/London' ? 'LDN' : 'UTC'}</span></summary><div className="absolute bottom-8 right-0 w-48 rounded-lg border border-slate-700 bg-slate-900 p-1.5 shadow-2xl"><p className="px-2 py-1 text-[9px] uppercase tracking-wider text-slate-600">Chart timezone</p>{timezones.map(zone => <button key={zone} type="button" onClick={event => { onTimezoneChange(zone); event.currentTarget.closest('details')?.removeAttribute('open') }} className={`flex min-h-8 w-full items-center rounded-md px-2 text-left font-mono text-[10px] ${timezone === zone ? 'bg-slate-800 text-white' : 'text-slate-400 hover:bg-slate-800'}`}>{zone}{timezone === zone && <span className="ml-auto">✓</span>}</button>)}</div></details>
}
