import { privateRequest, request } from '../auth/api'
import { boundedJson } from '../chat/aiApi'
export type Item={criterion:'specificity'|'evidence'|'risk'|'invalidation';score:number;evidence:string;feedback:string}
export type Result={kind:'evaluation'|'insufficient';summary:string;rubric:Item[];strengths:string[];improvements:string[];questions:string[];disclaimer:string}
export type Evaluation={journalId:string;requestId:string;expectedVersion:number;snapshotHash:string;provider:'gemini'|'openai';model:string;state:'PENDING'|'READY'|'INSUFFICIENT'|'FAILED'|'CANCELLED';errorCode:string|null;result:Result|null;score:number|null;createdAt:string;expiresAt:string;updatedAt:string}
const bad=()=>new Error('Invalid journal evaluation response. Reload before retrying.')
const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw bad();return v as Record<string,unknown>}
const exact=(v:Record<string,unknown>,keys:string[])=>{if(Object.keys(v).sort().join()!==[...keys].sort().join())throw bad()}
const uuid=(v:unknown)=>{if(typeof v!=='string'||!/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/.test(v))throw bad();return v}
const txt=(v:unknown,n:number)=>{if(typeof v!=='string'||!v.trim()||v.length>n)throw bad();return v}
const list=(v:unknown,n:number)=>{if(!Array.isArray(v)||v.length>4||v.some(x=>typeof x!=='string'||!x.trim()||x.length>n))throw bad();return v as string[]}
function parse(v:unknown):Evaluation{const x=obj(v);exact(x,['journalId','requestId','expectedVersion','snapshotHash','provider','model','state','errorCode','result','score','createdAt','expiresAt','updatedAt']);if(!['gemini','openai'].includes(String(x.provider))||!['PENDING','READY','INSUFFICIENT','FAILED','CANCELLED'].includes(String(x.state))||!Number.isInteger(x.expectedVersion)||(x.expectedVersion as number)<1||(x.expectedVersion as number)>100||!/^[0-9a-f]{64}$/.test(String(x.snapshotHash)))throw bad();let result:Result|null=null;if(x.result!==null){const q=obj(x.result);exact(q,['kind','summary','rubric','strengths','improvements','questions','disclaimer']);if(q.kind!=='evaluation'&&q.kind!=='insufficient')throw bad();const rubric=Array.isArray(q.rubric)?q.rubric.map(raw=>{const i=obj(raw);exact(i,['criterion','score','evidence','feedback']);if(!['specificity','evidence','risk','invalidation'].includes(String(i.criterion))||!Number.isInteger(i.score)||(i.score as number)<0||(i.score as number)>25)throw bad();return{criterion:i.criterion as Item['criterion'],score:i.score as number,evidence:txt(i.evidence,240),feedback:txt(i.feedback,300)}}):(()=>{throw bad()})();result={kind:q.kind,summary:txt(q.summary,1200),rubric,strengths:list(q.strengths,240),improvements:list(q.improvements,240),questions:list(q.questions,200),disclaimer:txt(q.disclaimer,500)}}const score=x.score===null?null:x.score as number;if(score!==null&&(!Number.isInteger(score)||score<0||score>100))throw bad();if((x.state==='READY'&&(!result||result.kind!=='evaluation'||result.rubric.map(i=>i.criterion).join()!=='specificity,evidence,risk,invalidation'||score!==result.rubric.reduce((s,i)=>s+i.score,0)))||(x.state==='INSUFFICIENT'&&(!result||result.kind!=='insufficient'||result.rubric.length||score!==null))||(['PENDING','FAILED','CANCELLED'].includes(String(x.state))&&(result!==null||score!==null)))throw bad();for(const key of ['createdAt','expiresAt','updatedAt'])if(!Number.isFinite(Date.parse(txt(x[key],64))))throw bad();return{journalId:uuid(x.journalId),requestId:uuid(x.requestId),expectedVersion:x.expectedVersion as number,snapshotHash:String(x.snapshotHash),provider:x.provider as Evaluation['provider'],model:txt(x.model,128),state:x.state as Evaluation['state'],errorCode:x.errorCode===null?null:txt(x.errorCode,32),result,score,createdAt:x.createdAt as string,expiresAt:x.expiresAt as string,updatedAt:x.updatedAt as string}}
async function post(path:string,body:object,account?:string){const token=obj(await boundedJson(await request('/auth/csrf')));if(token.headerName!=='X-CSRF-TOKEN'||typeof token.token!=='string')throw bad();return parse(await boundedJson(await privateRequest(account,path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':token.token},body:JSON.stringify(body),signal:AbortSignal.timeout(30_000)}),131072))}
const route=(id:string)=>`/journal/${uuid(id)}/evaluations`
export async function latest(id:string,account?:string){const r=await privateRequest(account,route(id));return r.status===204?null:parse(await boundedJson(r,131072))}
export const start=(id:string,version:number,requestId:string,account?:string)=>post(route(id),{requestId:uuid(requestId),expectedVersion:version},account)
export const cancel=(e:Evaluation,account?:string)=>post(`${route(e.journalId)}/${e.requestId}/cancel`,{},account)
